import type { Metadata } from "next";
import HomeReloadLink from "../home-reload-link";
import { database, ensureMediaTables, ensureMinistryProfileTables,ensurePastorPeopleTables } from "../api/_shared";
import { expandSearchTerm as expand, MAX_SEARCH_TERMS, normalizeSearchValue as normalize, searchTermCount, sqlMetadataSearchValue, sqlRelevance, tokenizeSearchQuery } from "../search-domain";
import SearchForm from "./search-form";
import SearchAnchorFocus from "./search-anchor-focus";
import SavedNavLink from "../saved-nav-link";
import SkipLink from "../skip-link";
import DailyMediaLink from "../daily-media-link";
import {hasAdminAccess} from "../admin-access";
import {ChurchControls,PastorControls} from "../admin/admin-controls";
import {sqlValidPastorName} from "../pastor-name";
import AdminSearchCard from "./admin-search-card";
import ChurchSaveButton from "../church/[id]/church-save-button";
import {churchHomepageUrls} from "../church-homepages";
import {safeHttpUrl} from "../safe-url";
import {ChurchCardContent,PastorCardContent} from "../directory-cards";
import {discoveryFilter,discoveryOrder,ensureSearchDiscoveryPools} from "../search-discovery-pools";
import DiscoveryRefreshButton from "./discovery-refresh-button";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"통합 검색 | airChurch",description:"교회, 목사, 지역, 교단, 말씀과 찬양을 한 번에 찾습니다.",robots:{index:false,follow:true}};

type ChurchResult={id:number;name:string;pastor:string;pastor_public_id:number|null;region:string;denomination:string;homepage_url:string|null;youtube_channel_id:string|null;priority_weight:number};
type VideoResult={youtube_id:string;title:string;published_at:string;church_id:number;church:string;pastor:string;region:string;denomination:string};
type PastorResult={person_id:number|null;public_id:number|null;role_id:number|null;church_id:number|null;minister_id:number|null;name:string;role_title:string;role_status:string;church:string|null;region:string|null;denomination:string|null;photo_url:string|null};

const regions=["전체","서울","부산","대구","인천","광주","대전","울산","세종","경기","강원","충북","충남","전북","전남","경북","경남","제주"];
const fieldScore=(field:string,candidates:string[],weight:number)=>{const value=normalize(field);return Math.max(0,...candidates.map((candidate)=>value===candidate?weight+70:value.startsWith(candidate)?weight+28:value.includes(candidate)?weight:0));};
const relevance=(church:ChurchResult,terms:string[])=>{const fields=[[church.name,40],[church.pastor,25],[church.region,15],[church.denomination,12]] as const;return terms.reduce((score,term)=>score+Math.max(0,...fields.map(([field,weight])=>fieldScore(field,expand(term),weight))),0);};
const matchLabels=(church:ChurchResult,terms:string[])=>{const fields=[["교회",church.name],["목사",church.pastor],["지역",church.region],["교단",church.denomination]] as const;return fields.filter(([,field])=>terms.some((term)=>expand(term).some((candidate)=>normalize(field).includes(candidate)))).map(([label])=>label);};
const videoMatchLabels=(video:VideoResult,terms:string[])=>{const fields=[["제목",video.title],["교회",video.church],["목사",video.pastor],["지역",video.region],["교단",video.denomination]] as const;return fields.filter(([,field])=>terms.some((term)=>expand(term).some((candidate)=>normalize(field).includes(candidate)))).map(([label])=>label);};

export default async function SearchPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const [params,isAdmin]=await Promise.all([searchParams,hasAdminAccess()]);
  const value=(key:string,max:number)=>String(Array.isArray(params[key])?params[key]?.[0]??"":params[key]??"").trim().slice(0,max);
  const pageNumber=(key:string)=>{const parsed=Number(value(key,5));return Number.isInteger(parsed)&&parsed>0?Math.min(parsed,1_000):1;};
  const q=value("q",100),region=value("region",40),denomination=value("denomination",100),terms=tokenizeSearchQuery(q);
  const isDiscovery=!q&&(!region||region==="전체")&&(!denomination||denomination==="전체 교단"),pageSize=isDiscovery?40:12,churchPage=pageNumber("churchPage"),sermonPage=pageNumber("sermonPage"),praisePage=pageNumber("praisePage");
  const bucket=(key:string)=>{const parsed=Number(value(key,2));return Number.isInteger(parsed)&&parsed>=0&&parsed<50?parsed:0;},churchSet=bucket("churchSet"),pastorSet=bucket("pastorSet"),sermonSet=bucket("sermonSet"),praiseSet=bucket("praiseSet");
  const churchOffset=(churchPage-1)*pageSize,sermonOffset=(sermonPage-1)*pageSize,praiseOffset=(praisePage-1)*pageSize;
  const searchWasTruncated=searchTermCount(q)>MAX_SEARCH_TERMS;
  const filters=(haystack:string)=>{const groups=terms.map(expand);const conditions=groups.map((group)=>`(${group.map(()=>`instr(${haystack},?)>0`).join(" OR ")})`);const bindings:string[]=groups.flat();if(region&&region!=="전체"){conditions.push("substr(c.region,1,length(?))=?");bindings.push(region,region);}if(denomination&&denomination!=="전체 교단"){conditions.push("c.denomination=?");bindings.push(denomination);}return {sql:conditions.length?` AND ${conditions.join(" AND ")}`:"",bindings};};
  const churchFilter=filters(sqlMetadataSearchValue("c.name","c.pastor","c.region","c.denomination")),videoFilter=filters(sqlMetadataSearchValue("c.name","c.pastor","c.region","c.denomination","v.title")),ministerFilter=filters(sqlMetadataSearchValue("p.name","p.role_title","c.name","c.region","c.denomination"));
  const personHaystack=sqlMetadataSearchValue("pp.name","r.role_title","r.church_name","r.region","r.denomination"),personGroups=terms.map(expand),personConditions=personGroups.map((group)=>`(${group.map(()=>`instr(${personHaystack},?)>0`).join(" OR ")})`),personBindings:string[]=personGroups.flat();
  if(region&&region!=="전체"){personConditions.push("substr(COALESCE(r.region,''),1,length(?))=?");personBindings.push(region,region);}if(denomination&&denomination!=="전체 교단"){personConditions.push("COALESCE(r.denomination,'')=?");personBindings.push(denomination);}
  const personFilter=personConditions.length?` AND ${personConditions.join(" AND ")}`:"";
  const groups=terms.map(expand),churchSqlScore=sqlRelevance([["c.name",40],["c.pastor",25],["c.region",15],["c.denomination",12]],groups),videoSqlScore=sqlRelevance([["v.title",45],["c.name",35],["c.pastor",24],["c.region",14],["c.denomination",12]],groups);
  const db=database();await Promise.all([ensureMediaTables(db),ensureMinistryProfileTables(db),ensurePastorPeopleTables(db)]);if(isDiscovery)await ensureSearchDiscoveryPools(db);
  const churchPool=isDiscovery?discoveryFilter("church",churchSet,"c.id"):"",pastorPool=isDiscovery?discoveryFilter("pastor",pastorSet,"pp.id"):"",sermonPool=isDiscovery?discoveryFilter("sermon",sermonSet,"v.id"):"",praisePool=isDiscovery?discoveryFilter("praise",praiseSet,"v.id"):"";
  const churchOrder=isDiscovery?discoveryOrder("church",churchSet,"c.id"):`(${churchSqlScore.sql}) DESC,c.priority_weight DESC,c.name,c.id`,pastorOrder=isDiscovery?discoveryOrder("pastor",pastorSet,"pp.id"):"CASE r.role_status WHEN 'current' THEN 0 ELSE 1 END,pp.name,r.id DESC",sermonOrder=isDiscovery?discoveryOrder("sermon",sermonSet,"v.id"):`(${videoSqlScore.sql}) DESC,v.published_at DESC,v.id DESC`,praiseOrder=isDiscovery?discoveryOrder("praise",praiseSet,"v.id"):`(${videoSqlScore.sql}) DESC,v.published_at DESC,v.id DESC`;
  const personRoleJoin=isDiscovery?"LEFT JOIN pastor_church_roles r ON r.id=(SELECT rr.id FROM pastor_church_roles rr WHERE rr.pastor_id=pp.id AND rr.review_status='approved' ORDER BY CASE rr.role_status WHEN 'current' THEN 0 ELSE 1 END,rr.id DESC LIMIT 1)":"LEFT JOIN pastor_church_roles r ON r.pastor_id=pp.id AND r.review_status='approved'";
  const [churches,personPastors,primaryPastors,ministryPastors,sermons,praises,denominationRows]=await Promise.all([
    db.prepare(`SELECT c.id,c.name,c.pastor,(SELECT COALESCE(pp.public_id,1000000+pp.id) FROM pastor_church_roles pr JOIN pastor_people pp ON pp.id=pr.pastor_id WHERE pr.church_id=c.id AND pr.review_status='approved' AND pp.review_status='approved' AND REPLACE(TRIM(CASE WHEN TRIM(pp.name) LIKE '%목사님' THEN SUBSTR(TRIM(pp.name),1,LENGTH(TRIM(pp.name))-3) WHEN TRIM(pp.name) LIKE '%목사' THEN SUBSTR(TRIM(pp.name),1,LENGTH(TRIM(pp.name))-2) ELSE TRIM(pp.name) END),' ','')=REPLACE(TRIM(CASE WHEN TRIM(c.pastor) LIKE '%목사님' THEN SUBSTR(TRIM(c.pastor),1,LENGTH(TRIM(c.pastor))-3) WHEN TRIM(c.pastor) LIKE '%목사' THEN SUBSTR(TRIM(c.pastor),1,LENGTH(TRIM(c.pastor))-2) ELSE TRIM(c.pastor) END),' ','') ORDER BY CASE pr.role_category WHEN 'current_primary' THEN 0 ELSE 1 END,CASE pr.role_status WHEN 'current' THEN 0 ELSE 1 END,pr.id DESC LIMIT 1) AS pastor_public_id,c.region,c.denomination,c.homepage_url,c.youtube_channel_id,c.priority_weight FROM churches c WHERE c.review_status='approved'${churchFilter.sql}${churchPool} ORDER BY ${churchOrder} LIMIT ${pageSize+1} OFFSET ${churchOffset}`).bind(...churchFilter.bindings,...(isDiscovery?[]:churchSqlScore.bindings)).all<ChurchResult>(),
    db.prepare(`SELECT pp.id AS person_id,COALESCE(pp.public_id,1000000+pp.id) AS public_id,r.id AS role_id,r.church_id,NULL AS minister_id,pp.name,r.role_title,r.role_status,r.church_name AS church,r.region,r.denomination,CASE WHEN pp.photo_review_status='approved' THEN pp.photo_url ELSE NULL END AS photo_url FROM pastor_people pp ${personRoleJoin} WHERE pp.review_status='approved' AND ${sqlValidPastorName("pp.name")}${personFilter}${pastorPool} ORDER BY ${pastorOrder} LIMIT ${isDiscovery?40:120}`).bind(...personBindings).all<PastorResult>(),
    db.prepare(`SELECT NULL AS person_id,NULL AS public_id,NULL AS role_id,c.id AS church_id,NULL AS minister_id,c.pastor AS name,'담임목사' AS role_title,'current' AS role_status,c.name AS church,c.region,c.denomination,NULL AS photo_url FROM churches c WHERE c.review_status='approved' AND ${isDiscovery?"0":"1"} AND ${sqlValidPastorName("c.pastor")}${churchFilter.sql} ORDER BY c.priority_weight DESC,c.name,c.id LIMIT 120`).bind(...churchFilter.bindings).all<PastorResult>(),
    db.prepare(`SELECT NULL AS person_id,NULL AS public_id,NULL AS role_id,c.id AS church_id,p.id AS minister_id,p.name,p.role_title,p.role_status,c.name AS church,c.region,c.denomination,NULL AS photo_url FROM church_ministry_profiles p JOIN churches c ON c.id=p.church_id WHERE c.review_status='approved' AND p.review_status='approved' AND ${isDiscovery?"0":"1"} AND ${sqlValidPastorName("p.name")}${ministerFilter.sql} ORDER BY c.priority_weight DESC,p.name,p.id LIMIT 120`).bind(...ministerFilter.bindings).all<PastorResult>(),
    db.prepare(`SELECT v.youtube_id,v.title,v.published_at,c.id AS church_id,c.name AS church,c.pastor,c.region,c.denomination FROM sermons v JOIN churches c ON c.id=v.church_id WHERE c.review_status='approved' AND v.status='published'${videoFilter.sql}${sermonPool} ORDER BY ${sermonOrder} LIMIT ${pageSize+1} OFFSET ${sermonOffset}`).bind(...videoFilter.bindings,...(isDiscovery?[]:videoSqlScore.bindings)).all<VideoResult>(),
    db.prepare(`SELECT v.youtube_id,v.title,v.published_at,c.id AS church_id,c.name AS church,c.pastor,c.region,c.denomination FROM praise_videos v JOIN churches c ON c.id=v.church_id WHERE c.review_status='approved' AND v.status='published'${videoFilter.sql}${praisePool} ORDER BY ${praiseOrder} LIMIT ${pageSize+1} OFFSET ${praiseOffset}`).bind(...videoFilter.bindings,...(isDiscovery?[]:videoSqlScore.bindings)).all<VideoResult>(),
    db.prepare("SELECT DISTINCT denomination FROM churches WHERE review_status='approved' AND denomination<>'' ORDER BY denomination").all<{denomination:string}>(),
  ]);
  const personResults=[...new Map(personPastors.results.map((item)=>[item.person_id,item])).values()],personIdentities=new Set(personResults.map((item)=>`${normalize(item.name)}|${normalize(item.church??"")}`));
  const legacyPastors=[...primaryPastors.results,...ministryPastors.results].filter((item)=>!personIdentities.has(`${normalize(item.name)}|${normalize(item.church??"")}`));
  const pastorResults=[...new Map([...personResults,...legacyPastors].map((item)=>[`${normalize(item.name)}|${item.church_id??-1}|${normalize(item.church??"")}`,item])).values()].sort((a,b)=>fieldScore(b.name,terms.flatMap(expand),40)-fieldScore(a.name,terms.flatMap(expand),40)||a.name.localeCompare(b.name,"ko"));
  const denominationOptions=["전체 교단",...denominationRows.results.map((row)=>row.denomination)];
  if(denomination&&denomination!=="전체 교단"&&!denominationOptions.includes(denomination))denominationOptions.push(denomination);
  const hasMoreChurches=churches.results.length>pageSize;churches.results=churches.results.slice(0,pageSize);
  const hasMoreSermons=sermons.results.length>pageSize;sermons.results=sermons.results.slice(0,pageSize);
  const hasMorePraises=praises.results.length>pageSize;praises.results=praises.results.slice(0,pageSize);
  let alternatives:ChurchResult[]=[];
  if(terms.length>1&&churches.results.length===0){const groups=terms.map(expand),haystack=sqlMetadataSearchValue("c.name","c.pastor","c.region","c.denomination");const relaxed=await db.prepare(`SELECT c.id,c.name,c.pastor,(SELECT COALESCE(pp.public_id,1000000+pp.id) FROM pastor_church_roles pr JOIN pastor_people pp ON pp.id=pr.pastor_id WHERE pr.church_id=c.id AND pr.review_status='approved' AND pp.review_status='approved' AND REPLACE(TRIM(CASE WHEN TRIM(pp.name) LIKE '%목사님' THEN SUBSTR(TRIM(pp.name),1,LENGTH(TRIM(pp.name))-3) WHEN TRIM(pp.name) LIKE '%목사' THEN SUBSTR(TRIM(pp.name),1,LENGTH(TRIM(pp.name))-2) ELSE TRIM(pp.name) END),' ','')=REPLACE(TRIM(CASE WHEN TRIM(c.pastor) LIKE '%목사님' THEN SUBSTR(TRIM(c.pastor),1,LENGTH(TRIM(c.pastor))-3) WHEN TRIM(c.pastor) LIKE '%목사' THEN SUBSTR(TRIM(c.pastor),1,LENGTH(TRIM(c.pastor))-2) ELSE TRIM(c.pastor) END),' ','') ORDER BY CASE pr.role_category WHEN 'current_primary' THEN 0 ELSE 1 END,CASE pr.role_status WHEN 'current' THEN 0 ELSE 1 END,pr.id DESC LIMIT 1) AS pastor_public_id,c.region,c.denomination,c.homepage_url,c.youtube_channel_id,c.priority_weight FROM churches c WHERE c.review_status='approved' AND (${groups.map((group)=>group.map(()=>`instr(${haystack},?)>0`).join(" OR ")).join(" OR ")}) LIMIT 80`).bind(...groups.flat()).all<ChurchResult>();alternatives=relaxed.results.sort((a,b)=>relevance(b,terms)-relevance(a,terms)||a.name.localeCompare(b.name,"ko")).slice(0,6);}
  const total=pastorResults.length+churches.results.length+sermons.results.length+praises.results.length;
  const filterUrl=(remove:"q"|"region"|"denomination")=>{const next=new URLSearchParams();if(remove!=="q"&&q)next.set("q",q);if(remove!=="region"&&region&&region!=="전체")next.set("region",region);if(remove!=="denomination"&&denomination&&denomination!=="전체 교단")next.set("denomination",denomination);const value=next.toString();return value?`/search?${value}`:"/search";};
  const activeFilters=[q?{key:"q" as const,label:`검색어 · ${q}`}:null,region&&region!=="전체"?{key:"region" as const,label:`지역 · ${region}`}:null,denomination&&denomination!=="전체 교단"?{key:"denomination" as const,label:`교단 · ${denomination}`}:null].filter((item):item is NonNullable<typeof item>=>Boolean(item));
  const pageUrl=(key:"churchPage"|"sermonPage"|"praisePage",page:number,anchor:string)=>{const next=new URLSearchParams();if(q)next.set("q",q);if(region&&region!=="전체")next.set("region",region);if(denomination&&denomination!=="전체 교단")next.set("denomination",denomination);if(churchPage>1)next.set("churchPage",String(churchPage));if(sermonPage>1)next.set("sermonPage",String(sermonPage));if(praisePage>1)next.set("praisePage",String(praisePage));if(page<=1)next.delete(key);else next.set(key,String(page));return `/search?${next.toString()}#${anchor}`;};
  const videoCard=(item:VideoResult,kind:"말씀"|"찬양")=>{const labels=videoMatchLabels(item,terms);return <DailyMediaLink className="search-result-video" href={`https://www.youtube.com/watch?v=${item.youtube_id}`} step={kind==="말씀"?"sermon":"praise"} key={`${kind}-${item.youtube_id}`}><img src={`https://i.ytimg.com/vi/${item.youtube_id}/mqdefault.jpg`} alt="" width={320} height={180} loading="lazy" decoding="async" referrerPolicy="no-referrer"/><span><small>{kind} · {item.church}</small><strong>{item.title}</strong>{labels.length>0&&<small className="search-video-match">일치 · {labels.join(" · ")}</small>}<em>{new Date(item.published_at).toLocaleDateString("ko-KR",{timeZone:"Asia/Seoul"})} · YouTube ↗</em></span></DailyMediaLink>};
  const churchCard=(church:ChurchResult,key:string,labels:string[],anchorId?:string)=>{const homepage=safeHttpUrl(churchHomepageUrls[church.name]||church.homepage_url);return <AdminSearchCard admin={isAdmin} linksOnly href={`/church/${church.id}`} label={church.name} className="home-style-church-card shared-church-card" key={key} controls={isAdmin?<ChurchControls id={church.id} name={church.name} pastor={church.pastor} region={church.region} denomination={church.denomination} status="approved" holdReason={null} holdNote={null} heldAt={null} priorityWeight={church.priority_weight}/>:undefined}><ChurchCardContent id={church.id} name={church.name} pastor={church.pastor} pastorHref={church.pastor_public_id!==null?`/pastors/${church.pastor_public_id}`:null} region={church.region} regionId={anchorId} denomination={church.denomination} homepageUrl={homepage} youtubeChannelId={church.youtube_channel_id} saveAction={<ChurchSaveButton id={church.id} name={church.name} pastor={church.pastor} region={church.region} compact/>} detail={labels.length>0?<small className="search-match-reason">일치 · {labels.join(" · ")}</small>:undefined}/></AdminSearchCard>};
  return <main className="search-page"><SkipLink/><SearchAnchorFocus/>
    <header className="site-header"><HomeReloadLink className="brand" ariaLabel="에어처치 첫 화면 새로 불러오기"><span className="brand-mark" aria-hidden="true"/><span>airchurch</span></HomeReloadLink><nav aria-label="주요 메뉴"><a href="/#sermons">말씀</a><a href="/#praises">찬양</a><a href="/#church-directory">교회</a><a href="/#pastor-directory">목회자</a><a href="/#church-news">교계소식</a><a href="/#community">공동체</a><a href="/#goodshare">착한나눔</a><a href="/#vision">소개</a></nav><nav className="header-admin-links" aria-label="운영 메뉴"><SavedNavLink/><a href="/about">운영 안내</a><a href="/contact">문의</a></nav><a className="mobile-menu-button" href="/">홈으로</a></header>
    <section className="search-page-hero" id="primary-content" tabIndex={-1}><span>CHRISTIAN PORTAL SEARCH</span><h1>교회·목회자·말씀·찬양을<br/>한 번에 찾습니다</h1><SearchForm q={q} region={region} denomination={denomination} regions={regions} denominations={denominationOptions}/><p>{q||region&&region!=="전체"||denomination&&denomination!=="전체 교단"?`관련도 순으로 현재 페이지의 결과 ${total}개를 보여드립니다.`:"최근 교회·목회자·말씀·찬양을 보여드립니다."}</p>{q&&!terms.length&&<p className="search-term-notice" role="status">일반 표현은 제외하고 최근 콘텐츠를 보여드립니다. 교회명·목사·지역·교단을 함께 적으면 더 정확합니다.</p>}{searchWasTruncated&&<p className="search-term-notice" role="status">검색 성능을 위해 앞의 {MAX_SEARCH_TERMS}개 조건을 반영했습니다.</p>}{activeFilters.length>0&&<div className="search-active-filters" aria-label="현재 검색 조건">{activeFilters.map((item)=><a href={filterUrl(item.key)} key={item.key}>{item.label}<span aria-hidden="true">×</span></a>)}{activeFilters.length>1&&<a className="clear" href="/search">조건 전체 해제</a>}</div>}<nav className="search-result-jumps" aria-label="검색 결과 종류"><a href="#pastor-results">목회자 <b>{pastorResults.length}</b></a><a href="#church-results">교회 <b>{churches.results.length}</b></a><a href="#sermon-results">말씀 <b>{sermons.results.length}</b></a><a href="#praise-results">찬양 <b>{praises.results.length}</b></a></nav></section>
    <nav className="search-mobile-jumps" aria-label="모바일 검색 결과 이동"><a href="#pastor-results">목회자 <b>{pastorResults.length}</b></a><a href="#church-results">교회 <b>{churches.results.length}</b></a><a href="#sermon-results">말씀 <b>{sermons.results.length}</b></a><a href="#praise-results">찬양 <b>{praises.results.length}</b></a></nav>
    {total===0&&activeFilters.length>0&&<section className="search-recovery" role="status"><span className="section-kicker">SEARCH AGAIN</span><h2>검색 조건을 하나씩 넓혀보세요</h2><p>공백은 구분하지 않으므로 교회명·목사·지역·교단 중 한 단어만 남겨도 됩니다.</p><div>{activeFilters.map((item)=><a href={filterUrl(item.key)} key={`recovery-${item.key}`}>{item.label} 빼고 다시 찾기</a>)}<a className="primary" href="/search">최근 콘텐츠 보기</a></div></section>}
    <section className="search-results" id="pastor-results"><div className="search-results-heading"><div><span className="section-kicker">PASTORS</span><h2>목회자</h2></div>{isDiscovery?<DiscoveryRefreshButton parameter="pastorSet" anchor="pastor-results" label="목회자"/>:<b>{pastorResults.length}명</b>}</div><div className="search-church-grid">{pastorResults.map((pastor)=>{const name=pastor.name.replace(/\s*목사(?:님)?$/u,""),href=pastor.person_id&&pastor.public_id!==null?`/pastors/${pastor.public_id}`:`/church/${pastor.church_id}`,photo=pastor.photo_url&&pastor.public_id!==null?`/api/pastor-photo/${pastor.public_id}`:"/pastor-silhouette-soft.png",key=`${normalize(pastor.name)}-${pastor.church_id??-1}-${normalize(pastor.church??"")}`,manageable=Boolean(isAdmin&&pastor.person_id);return <AdminSearchCard admin={manageable} linksOnly href={href} label={`${name} 목회자`} className="pastor-home-card shared-pastor-card" key={key} controls={manageable&&pastor.person_id?<PastorControls id={pastor.person_id} roleId={pastor.role_id} name={pastor.name} roleTitle={pastor.role_title} churchName={pastor.church} region={pastor.region} denomination={pastor.denomination} roleStatus={pastor.role_status} status="approved"/>:undefined}><PastorCardContent name={name} href={href} photoUrl={photo} hasPhoto={Boolean(pastor.photo_url)} roleStatus={pastor.role_status} roles={[pastor.role_title]} churchName={pastor.church} churchHref={pastor.church_id?`/church/${pastor.church_id}`:null} region={pastor.region} denomination={pastor.denomination}/></AdminSearchCard>})}{!pastorResults.length&&<p className="empty">공식 출처 검토가 끝난 목회자 정보가 없습니다.</p>}</div></section>
    <section className="search-results" id="church-results"><div className="search-results-heading"><div><span className="section-kicker">CHURCHES</span><h2>교회</h2></div>{isDiscovery?<DiscoveryRefreshButton parameter="churchSet" anchor="church-results" label="교회"/>:<b>{churchPage}페이지 · {churches.results.length}곳</b>}</div><div className="church-directory-grid search-church-directory-grid">{churches.results.map((church,index)=>churchCard(church,String(church.id),matchLabels(church,terms),`church-result-${index+1}`))}{!churches.results.length&&<p className="empty">조건에 맞는 공개 교회가 없습니다.</p>}</div>{!isDiscovery&&<nav className="search-pagination" aria-label="교회 검색 페이지">{churchPage>1&&<a href={pageUrl("churchPage",churchPage-1,"church-result-1")}>← 이전</a>}<span>{churchPage}페이지</span>{hasMoreChurches&&<a href={pageUrl("churchPage",churchPage+1,"church-result-1")}>다음 12곳 →</a>}</nav>}</section>
    {alternatives.length>0&&<section className="search-results search-alternatives"><div className="search-results-heading"><div><span className="section-kicker">조건을 조금 넓혀서</span><h2>일부 검색어와 가까운 교회</h2></div><b>{alternatives.length}곳 제안</b></div><p className="search-alternative-note">입력한 조건을 모두 만족하는 교회가 없어, 일부 단어가 교회·목사·지역·교단 정보와 일치하는 곳을 보여드립니다.</p><div className="church-directory-grid search-church-directory-grid">{alternatives.map((church)=>churchCard(church,`alternative-${church.id}`,matchLabels(church,terms)))}</div></section>}
    <section className="search-results" id="sermon-results"><div className="search-results-heading"><div><span className="section-kicker">SERMONS</span><h2>말씀</h2></div>{isDiscovery?<DiscoveryRefreshButton parameter="sermonSet" anchor="sermon-results" label="말씀"/>:<b>{sermonPage}페이지 · {sermons.results.length}편</b>}</div><div className="search-video-grid">{sermons.results.map((item,index)=><div id={`sermon-result-${index+1}`} tabIndex={-1} key={item.youtube_id}>{videoCard(item,"말씀")}</div>)}{!sermons.results.length&&<p className="empty">조건에 맞는 말씀이 없습니다.</p>}</div>{!isDiscovery&&<nav className="search-pagination" aria-label="말씀 검색 페이지">{sermonPage>1&&<a href={pageUrl("sermonPage",sermonPage-1,"sermon-result-1")}>← 이전</a>}<span>{sermonPage}페이지</span>{hasMoreSermons&&<a href={pageUrl("sermonPage",sermonPage+1,"sermon-result-1")}>다음 12편 →</a>}</nav>}</section>
    <section className="search-results" id="praise-results"><div className="search-results-heading"><div><span className="section-kicker">PRAISE</span><h2>찬양</h2></div>{isDiscovery?<DiscoveryRefreshButton parameter="praiseSet" anchor="praise-results" label="찬양"/>:<b>{praisePage}페이지 · {praises.results.length}편</b>}</div><div className="search-video-grid">{praises.results.map((item,index)=><div id={`praise-result-${index+1}`} tabIndex={-1} key={item.youtube_id}>{videoCard(item,"찬양")}</div>)}{!praises.results.length&&<p className="empty">조건에 맞는 찬양이 없습니다.</p>}</div>{!isDiscovery&&<nav className="search-pagination" aria-label="찬양 검색 페이지">{praisePage>1&&<a href={pageUrl("praisePage",praisePage-1,"praise-result-1")}>← 이전</a>}<span>{praisePage}페이지</span>{hasMorePraises&&<a href={pageUrl("praisePage",praisePage+1,"praise-result-1")}>다음 12편 →</a>}</nav>}</section>
    <footer id="page-bottom"><HomeReloadLink className="brand footer-brand"><span className="brand-mark" aria-hidden="true"/><span>airchurch</span></HomeReloadLink><p>airchurch.net · goodshare.net · linechurch.net<br/>공개 자료를 정리해 사람과 교회를 잇는 크리스천 포털</p><div className="footer-meta"><div className="footer-links"><a href="/about">운영 안내</a><a href="/community-guidelines">공동체 안전</a><a href="/privacy">개인정보처리방침</a><a href="/copyright">저작권 원칙</a><a href="/terms">이용약관</a><a href="/contact">문의</a><a href="/admin">관리자</a><a href="/pastor">목사님</a></div><a className="footer-pastor-link" href="/pastors/2">협동 목사 : 김민석 <span>(바로가기)</span></a></div></footer>
  </main>;
}
