import type { Metadata } from "next";
import Link from "next/link";
import HomeReloadLink from "../home-reload-link";
import { database, ensurePraiseTables, ensureSermonTables } from "../api/_shared";
import { expandSearchTerm as expand, MAX_SEARCH_TERMS, normalizeSearchValue as normalize, searchTermCount, sqlMetadataSearchValue, sqlRelevance, tokenizeSearchQuery } from "../search-domain";
import SearchForm from "./search-form";
import SearchAnchorFocus from "./search-anchor-focus";
import SavedNavLink from "../saved-nav-link";
import SkipLink from "../skip-link";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"통합 검색 | airChurch",description:"교회, 목사, 지역, 교단, 말씀과 찬양을 한 번에 찾습니다.",robots:{index:false,follow:true}};

type ChurchResult={id:number;name:string;pastor:string;region:string;denomination:string;priority_weight:number};
type VideoResult={youtube_id:string;title:string;published_at:string;church_id:number;church:string;pastor:string;region:string;denomination:string};

const regions=["전체","서울","부산","대구","인천","광주","대전","울산","세종","경기","강원","충북","충남","전북","전남","경북","경남","제주"];
const fieldScore=(field:string,candidates:string[],weight:number)=>{const value=normalize(field);return Math.max(0,...candidates.map((candidate)=>value===candidate?weight+70:value.startsWith(candidate)?weight+28:value.includes(candidate)?weight:0));};
const relevance=(church:ChurchResult,terms:string[])=>{const fields=[[church.name,40],[church.pastor,25],[church.region,15],[church.denomination,12]] as const;return terms.reduce((score,term)=>score+Math.max(0,...fields.map(([field,weight])=>fieldScore(field,expand(term),weight))),0);};
const videoRelevance=(video:VideoResult,terms:string[])=>{const fields=[[video.title,45],[video.church,35],[video.pastor,24],[video.region,14],[video.denomination,12]] as const;return terms.reduce((score,term)=>score+Math.max(0,...fields.map(([field,weight])=>fieldScore(field,expand(term),weight))),0);};
const matchLabels=(church:ChurchResult,terms:string[])=>{const fields=[["교회",church.name],["목사",church.pastor],["지역",church.region],["교단",church.denomination]] as const;return fields.filter(([,field])=>terms.some((term)=>expand(term).some((candidate)=>normalize(field).includes(candidate)))).map(([label])=>label);};
const videoMatchLabels=(video:VideoResult,terms:string[])=>{const fields=[["제목",video.title],["교회",video.church],["목사",video.pastor],["지역",video.region],["교단",video.denomination]] as const;return fields.filter(([,field])=>terms.some((term)=>expand(term).some((candidate)=>normalize(field).includes(candidate)))).map(([label])=>label);};

export default async function SearchPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const params=await searchParams;
  const value=(key:string,max:number)=>String(Array.isArray(params[key])?params[key]?.[0]??"":params[key]??"").trim().slice(0,max);
  const displayLimit=(key:string,max:number)=>{const parsed=Number(value(key,3));return parsed>=12&&parsed<=max&&(parsed%12===0||parsed===max)?parsed:12;};
  const churchLimit=displayLimit("churchLimit",200),sermonLimit=displayLimit("sermonLimit",120),praiseLimit=displayLimit("praiseLimit",80);
  const q=value("q",100),region=value("region",40),denomination=value("denomination",100),terms=tokenizeSearchQuery(q);
  const searchWasTruncated=searchTermCount(q)>MAX_SEARCH_TERMS;
  const filters=(haystack:string)=>{const groups=terms.map(expand);const conditions=[...(q&&!terms.length?["0=1"]:[]),...groups.map((group)=>`(${group.map(()=>`instr(${haystack},?)>0`).join(" OR ")})`)];const bindings:string[]=groups.flat();if(region&&region!=="전체"){conditions.push("substr(c.region,1,length(?))=?");bindings.push(region,region);}if(denomination&&denomination!=="전체 교단"){conditions.push("c.denomination=?");bindings.push(denomination);}return {sql:conditions.length?` AND ${conditions.join(" AND ")}`:"",bindings};};
  const churchFilter=filters(sqlMetadataSearchValue("c.name","c.pastor","c.region","c.denomination")),videoFilter=filters(sqlMetadataSearchValue("c.name","c.pastor","c.region","c.denomination","v.title"));
  const groups=terms.map(expand),churchSqlScore=sqlRelevance([["c.name",40],["c.pastor",25],["c.region",15],["c.denomination",12]],groups),videoSqlScore=sqlRelevance([["v.title",45],["c.name",35],["c.pastor",24],["c.region",14],["c.denomination",12]],groups);
  const db=database();await Promise.all([ensureSermonTables(db),ensurePraiseTables(db)]);
  const [churches,sermons,praises,denominationRows]=await Promise.all([
    db.prepare(`SELECT c.id,c.name,c.pastor,c.region,c.denomination,c.priority_weight FROM churches c WHERE c.review_status='approved'${churchFilter.sql} ORDER BY (${churchSqlScore.sql}) DESC,c.priority_weight DESC,c.name LIMIT 200`).bind(...churchFilter.bindings,...churchSqlScore.bindings).all<ChurchResult>(),
    db.prepare(`SELECT v.youtube_id,v.title,v.published_at,c.id AS church_id,c.name AS church,c.pastor,c.region,c.denomination FROM sermons v JOIN churches c ON c.id=v.church_id WHERE c.review_status='approved' AND v.status='published'${videoFilter.sql} ORDER BY (${videoSqlScore.sql}) DESC,v.published_at DESC LIMIT 120`).bind(...videoFilter.bindings,...videoSqlScore.bindings).all<VideoResult>(),
    db.prepare(`SELECT v.youtube_id,v.title,v.published_at,c.id AS church_id,c.name AS church,c.pastor,c.region,c.denomination FROM praise_videos v JOIN churches c ON c.id=v.church_id WHERE c.review_status='approved' AND v.status='published'${videoFilter.sql} ORDER BY (${videoSqlScore.sql}) DESC,v.published_at DESC LIMIT 80`).bind(...videoFilter.bindings,...videoSqlScore.bindings).all<VideoResult>(),
    db.prepare("SELECT DISTINCT denomination FROM churches WHERE review_status='approved' AND denomination<>'' ORDER BY denomination").all<{denomination:string}>(),
  ]);
  const denominationOptions=["전체 교단",...denominationRows.results.map((row)=>row.denomination)];
  if(denomination&&denomination!=="전체 교단"&&!denominationOptions.includes(denomination))denominationOptions.push(denomination);
  churches.results.sort((a,b)=>relevance(b,terms)-relevance(a,terms)||b.priority_weight-a.priority_weight||a.name.localeCompare(b.name,"ko"));const hasMoreChurches=churches.results.length>churchLimit;churches.results=churches.results.slice(0,churchLimit);
  sermons.results.sort((a,b)=>videoRelevance(b,terms)-videoRelevance(a,terms)||Date.parse(b.published_at)-Date.parse(a.published_at));const hasMoreSermons=sermons.results.length>sermonLimit;sermons.results=sermons.results.slice(0,sermonLimit);
  praises.results.sort((a,b)=>videoRelevance(b,terms)-videoRelevance(a,terms)||Date.parse(b.published_at)-Date.parse(a.published_at));const hasMorePraises=praises.results.length>praiseLimit;praises.results=praises.results.slice(0,praiseLimit);
  let alternatives:ChurchResult[]=[];
  if(terms.length>1&&churches.results.length===0){const groups=terms.map(expand),haystack=sqlMetadataSearchValue("c.name","c.pastor","c.region","c.denomination");const relaxed=await db.prepare(`SELECT c.id,c.name,c.pastor,c.region,c.denomination,c.priority_weight FROM churches c WHERE c.review_status='approved' AND (${groups.map((group)=>group.map(()=>`instr(${haystack},?)>0`).join(" OR ")).join(" OR ")}) LIMIT 80`).bind(...groups.flat()).all<ChurchResult>();alternatives=relaxed.results.sort((a,b)=>relevance(b,terms)-relevance(a,terms)||a.name.localeCompare(b.name,"ko")).slice(0,6);}
  const total=churches.results.length+sermons.results.length+praises.results.length;
  const filterUrl=(remove:"q"|"region"|"denomination")=>{const next=new URLSearchParams();if(remove!=="q"&&q)next.set("q",q);if(remove!=="region"&&region&&region!=="전체")next.set("region",region);if(remove!=="denomination"&&denomination&&denomination!=="전체 교단")next.set("denomination",denomination);const value=next.toString();return value?`/search?${value}`:"/search";};
  const activeFilters=[q?{key:"q" as const,label:`검색어 · ${q}`}:null,region&&region!=="전체"?{key:"region" as const,label:`지역 · ${region}`}:null,denomination&&denomination!=="전체 교단"?{key:"denomination" as const,label:`교단 · ${denomination}`}:null].filter((item):item is NonNullable<typeof item>=>Boolean(item));
  const moreUrl=(key:"churchLimit"|"sermonLimit"|"praiseLimit",limit:number,max:number,anchorPrefix:string)=>{const next=new URLSearchParams();if(q)next.set("q",q);if(region&&region!=="전체")next.set("region",region);if(denomination&&denomination!=="전체 교단")next.set("denomination",denomination);if(churchLimit>12)next.set("churchLimit",String(churchLimit));if(sermonLimit>12)next.set("sermonLimit",String(sermonLimit));if(praiseLimit>12)next.set("praiseLimit",String(praiseLimit));next.set(key,String(Math.min(max,limit+12)));return `/search?${next.toString()}#${anchorPrefix}-${limit+1}`;};
  const videoCard=(item:VideoResult,kind:string)=>{const labels=videoMatchLabels(item,terms);return <a className="search-result-video" href={`https://www.youtube.com/watch?v=${item.youtube_id}`} target="_blank" rel="noopener noreferrer" key={`${kind}-${item.youtube_id}`}><img src={`https://i.ytimg.com/vi/${item.youtube_id}/mqdefault.jpg`} alt="" width={320} height={180} loading="lazy" decoding="async" referrerPolicy="no-referrer"/><span><small>{kind} · {item.church}</small><strong>{item.title}</strong>{labels.length>0&&<small className="search-video-match">일치 · {labels.join(" · ")}</small>}<em>{new Date(item.published_at).toLocaleDateString("ko-KR",{timeZone:"Asia/Seoul"})} · YouTube ↗</em></span></a>};
  return <main className="search-page"><SkipLink/><SearchAnchorFocus/>
    <header className="search-page-header"><HomeReloadLink className="brand"><span className="brand-mark" aria-hidden="true"/><span>airchurch</span></HomeReloadLink><nav><Link href="/#sermons">말씀</Link><Link href="/#church-directory">교회 찾기</Link><SavedNavLink/><Link href="/#community">공동체</Link></nav><Link href="/">홈으로</Link></header>
    <section className="search-page-hero" id="primary-content" tabIndex={-1}><span>CHRISTIAN PORTAL SEARCH</span><h1>교회와 말씀을<br/>한 번에 찾습니다</h1><SearchForm q={q} region={region} denomination={denomination} regions={regions} denominations={denominationOptions}/><p>{q||region&&region!=="전체"||denomination&&denomination!=="전체 교단"?`관련도 높은 결과 ${total}개를 먼저 보여드립니다.`:"최근 교회·말씀·찬양을 보여드립니다."}</p>{searchWasTruncated&&<p className="search-term-notice" role="status">검색 성능을 위해 앞의 {MAX_SEARCH_TERMS}개 조건을 반영했습니다.</p>}{activeFilters.length>0&&<div className="search-active-filters" aria-label="현재 검색 조건">{activeFilters.map((item)=><a href={filterUrl(item.key)} key={item.key}>{item.label}<span aria-hidden="true">×</span></a>)}{activeFilters.length>1&&<a className="clear" href="/search">조건 전체 해제</a>}</div>}<nav className="search-result-jumps" aria-label="검색 결과 종류"><a href="#church-results">교회 <b>{churches.results.length}</b></a><a href="#sermon-results">말씀 <b>{sermons.results.length}</b></a><a href="#praise-results">찬양 <b>{praises.results.length}</b></a></nav></section>
    <nav className="search-mobile-jumps" aria-label="모바일 검색 결과 이동"><a href="#church-results">교회 <b>{churches.results.length}</b></a><a href="#sermon-results">말씀 <b>{sermons.results.length}</b></a><a href="#praise-results">찬양 <b>{praises.results.length}</b></a></nav>
    {total===0&&activeFilters.length>0&&<section className="search-recovery" role="status"><span className="section-kicker">SEARCH AGAIN</span><h2>검색 조건을 하나씩 넓혀보세요</h2><p>공백은 구분하지 않으므로 교회명·목사·지역·교단 중 한 단어만 남겨도 됩니다.</p><div>{activeFilters.map((item)=><Link href={filterUrl(item.key)} key={`recovery-${item.key}`}>{item.label} 빼고 다시 찾기</Link>)}<Link className="primary" href="/search">최근 콘텐츠 보기</Link></div></section>}
    <section className="search-results" id="church-results"><div className="search-results-heading"><div><span className="section-kicker">CHURCHES</span><h2>교회</h2></div><b>{churches.results.length}곳 표시</b></div><div className="search-church-grid">{churches.results.map((church,index)=>{const labels=matchLabels(church,terms);return <a href={`/church/${church.id}`} id={`church-result-${index+1}`} key={church.id}><span>{church.region}</span><strong>{church.name}</strong><p>{church.pastor}</p><small>{church.denomination}</small>{labels.length>0&&<small className="search-match-reason">일치 · {labels.join(" · ")}</small>}<em>교회 상세 보기 →</em></a>})}{!churches.results.length&&<p className="empty">조건에 맞는 공개 교회가 없습니다.</p>}</div>{hasMoreChurches&&<a className="search-more-results" href={moreUrl("churchLimit",churchLimit,200,"church-result")}>교회 {Math.min(12,200-churchLimit)}곳 더 보기</a>}</section>
    {alternatives.length>0&&<section className="search-results search-alternatives"><div className="search-results-heading"><div><span className="section-kicker">조건을 조금 넓혀서</span><h2>일부 검색어와 가까운 교회</h2></div><b>{alternatives.length}곳 제안</b></div><p className="search-alternative-note">입력한 조건을 모두 만족하는 교회가 없어, 일부 단어가 교회·목사·지역·교단 정보와 일치하는 곳을 보여드립니다.</p><div className="search-church-grid">{alternatives.map((church)=>{const labels=matchLabels(church,terms);return <a href={`/church/${church.id}`} key={`alternative-${church.id}`}><span>{church.region}</span><strong>{church.name}</strong><p>{church.pastor}</p><small>{church.denomination}</small><small className="search-match-reason">가까운 조건 · {labels.join(" · ")}</small><em>교회 상세 보기 →</em></a>})}</div></section>}
    <section className="search-results" id="sermon-results"><div className="search-results-heading"><div><span className="section-kicker">SERMONS</span><h2>말씀</h2></div><b>{sermons.results.length}편 표시</b></div><div className="search-video-grid">{sermons.results.map((item,index)=><div id={`sermon-result-${index+1}`} tabIndex={-1} key={item.youtube_id}>{videoCard(item,"말씀")}</div>)}{!sermons.results.length&&<p className="empty">조건에 맞는 말씀이 없습니다.</p>}</div>{hasMoreSermons&&<a className="search-more-results" href={moreUrl("sermonLimit",sermonLimit,120,"sermon-result")}>말씀 12편 더 보기</a>}</section>
    <section className="search-results" id="praise-results"><div className="search-results-heading"><div><span className="section-kicker">PRAISE</span><h2>찬양</h2></div><b>{praises.results.length}편 표시</b></div><div className="search-video-grid">{praises.results.map((item,index)=><div id={`praise-result-${index+1}`} tabIndex={-1} key={item.youtube_id}>{videoCard(item,"찬양")}</div>)}{!praises.results.length&&<p className="empty">조건에 맞는 찬양이 없습니다.</p>}</div>{hasMorePraises&&<a className="search-more-results" href={moreUrl("praiseLimit",praiseLimit,80,"praise-result")}>찬양 {Math.min(12,80-praiseLimit)}편 더 보기</a>}</section>
    <footer className="church-detail-footer"><Link href="/">airChurch 홈</Link><span>공개 자료와 공식 채널을 기준으로 검색합니다.</span></footer>
  </main>;
}
