import type {Metadata} from "next";
import {hasAdminAccess} from "../../admin-access";
import {database,ensureAdminTables} from "../../api/_shared";
import AdminLogin from "../admin-login";
import {PastorIdentityControls} from "../admin-controls";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"목회자 동일인 검토 | airChurch",robots:{index:false,follow:false}};
type IdentityRow={id:number;evidence_type:string;evidence_value:string;left_id:number;left_name:string;left_church:string|null;left_role:string|null;right_id:number;right_name:string;right_church:string|null;right_role:string|null};
export default async function PastorIdentityReviewPage(){if(!await hasAdminAccess())return <AdminLogin/>;const db=database();await ensureAdminTables(db);const [count,rows]=await Promise.all([db.prepare("SELECT COUNT(*) AS count FROM pastor_identity_candidates WHERE status='pending'").first<{count:number}>(),db.prepare("SELECT i.id,i.evidence_type,i.evidence_value,l.id AS left_id,l.name AS left_name,ll.church_name AS left_church,ll.role_title AS left_role,r.id AS right_id,r.name AS right_name,rr.church_name AS right_church,rr.role_title AS right_role FROM pastor_identity_candidates i JOIN pastor_people l ON l.id=i.left_pastor_id JOIN pastor_people r ON r.id=i.right_pastor_id LEFT JOIN pastor_church_roles ll ON ll.id=(SELECT x.id FROM pastor_church_roles x WHERE x.pastor_id=l.id ORDER BY CASE x.role_status WHEN 'current' THEN 0 ELSE 1 END,x.id DESC LIMIT 1) LEFT JOIN pastor_church_roles rr ON rr.id=(SELECT x.id FROM pastor_church_roles x WHERE x.pastor_id=r.id ORDER BY CASE x.role_status WHEN 'current' THEN 0 ELSE 1 END,x.id DESC LIMIT 1) WHERE i.status='pending' ORDER BY i.created_at,i.id LIMIT 100").all<IdentityRow>()]);return <main className="admin-shell"><header className="admin-header"><a className="brand" href="/admin"><span className="brand-mark" aria-hidden="true"/><span>airchurch</span></a><div><span>목회자 동일인 검토</span><a href="/admin">관리자로 돌아가기</a></div></header><section className="admin-panel"><div className="admin-panel-title"><div><small>IDENTITY LINKS</small><h1>같은 사람의 사역 이력 연결</h1><p>이름만으로 합치지 않습니다. 정확히 같은 공식 사진 파일이나 공식 이동 기록 등 근거를 확인한 뒤 판정합니다. 판정해도 원본 인물은 삭제하지 않습니다.</p></div><span>대기 {Number(count?.count??0).toLocaleString("ko-KR")}건 · 100건 표시</span></div><div className="review-list">{rows.results.length?rows.results.map((item)=><article key={item.id}><div><span>{item.evidence_type==="exact_official_photo_sha256"?"동일한 공식 사진 파일":"공식 이력 근거"}</span><small>근거 {item.evidence_value.slice(0,12)}…</small></div><div className="admin-summary-line"><a href={`/pastors/p/${item.left_id}`}><strong>{item.left_name}</strong><span>{item.left_role??"직분 확인 중"} · {item.left_church??"교회 연결 전"}</span></a><span>↔</span><a href={`/pastors/p/${item.right_id}`}><strong>{item.right_name}</strong><span>{item.right_role??"직분 확인 중"} · {item.right_church??"교회 연결 전"}</span></a></div><PastorIdentityControls id={item.id}/></article>):<p className="admin-empty">동일인 연결 검토 대기가 없습니다.</p>}</div></section></main>;}
