"use client";

import {FormEvent,useEffect,useRef,useState} from "react";
import PastorDirectoryCard from "../pastor-directory-card";

export type AdminPastorItem={id:number;public_id:number;role_id:number|null;church_id:number|null;name:string;review_status:string;photo_url:string|null;photo_review_status:string;role_title:string|null;role_status:string|null;church_name:string|null;region:string|null;denomination:string|null;source_url:string|null};
type Props={initialItems:AdminPastorItem[];total:number};

function stateLabel(status:string){return status==="approved"?"공개":status==="pending"?"검토 중":status==="removed"?"보류":"비공개";}

export default function AdminPastorDirectory({initialItems,total}:Props){
  const [items,setItems]=useState(initialItems),[query,setQuery]=useState(""),[appliedQuery,setAppliedQuery]=useState(""),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(initialItems.length||1),[resultTotal,setResultTotal]=useState(total),[loading,setLoading]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<Set<number>>(()=>new Set()),[batchBusy,setBatchBusy]=useState(false);
  const requestRef=useRef<AbortController|null>(null),pages=Math.max(1,Math.ceil(resultTotal/pageSize));
  async function load(nextQuery:string,nextPage:number){requestRef.current?.abort();const controller=new AbortController();requestRef.current=controller;setLoading(true);setError("");setSelected(new Set());const params=new URLSearchParams({page:String(nextPage)});if(nextQuery.trim())params.set("q",nextQuery.trim());else params.set("bucket",String(Math.floor(Math.random()*50)));try{const response=await fetch(`/api/admin/pastors?${params}`,{cache:"no-store",signal:controller.signal}),data=await response.json() as {items?:AdminPastorItem[];total?:number;page?:number;pageSize?:number;error?:string};if(!response.ok)throw new Error(data.error||"목회자 목록을 불러오지 못했습니다.");setItems(data.items??[]);setResultTotal(data.total??0);setPageSize(data.pageSize??24);setPage(data.page??nextPage);setAppliedQuery(nextQuery.trim());}catch(reason){if((reason as {name?:string}).name!=="AbortError")setError((reason as Error).message);}finally{if(!controller.signal.aborted)setLoading(false);}}
  useEffect(()=>()=>requestRef.current?.abort(),[]);
  function submit(event:FormEvent){event.preventDefault();void load(query,1);}
  function reset(){requestRef.current?.abort();setQuery("");setAppliedQuery("");setItems(initialItems);setResultTotal(total);setPageSize(initialItems.length||1);setPage(1);setLoading(false);setError("");setSelected(new Set());}
  function toggleSelected(id:number,checked:boolean){setSelected((current)=>{const next=new Set(current);if(checked)next.add(id);else next.delete(id);return next;});}
  async function runBatch(status:"approved"|"removed"|"deleted") {const ids=[...selected];if(!ids.length)return;const action=status==="approved"?"공개":status==="removed"?"보류":"삭제";if(!window.confirm(`선택한 ${ids.length}명의 목회자를 ${action}할까요?`))return;setBatchBusy(true);setError("");try{const response=await fetch("/api/admin/manage",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"pastor-batch",ids,status})}),result=await response.json() as {error?:string;updated?:number[];failed?:number[]};if(!response.ok)throw new Error(result.error||"처리하지 못했습니다.");window.alert(`${result.updated?.length??0}명을 ${action}했습니다.${result.failed?.length?` ${result.failed.length}명은 이미 상태가 같거나 없어 제외했습니다.`:""}`);await load(appliedQuery,page);}catch(reason){setError((reason as Error).message);}finally{setBatchBusy(false);}}
  return <>
    <form className="admin-list-search" role="search" onSubmit={submit}><label><span className="sr-only">목회자 검색</span><input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} aria-controls="admin-pastor-list" placeholder="이름, 교회, 직분, 지역, 교단"/></label><span className="admin-search-count" aria-live="polite">{loading?"검색 중":`${items.length}/${resultTotal}`}</span><button type="submit" disabled={loading}>검색</button>{(query||appliedQuery)&&<button type="button" onClick={reset}>초기화</button>}{!query&&!appliedQuery&&<button className="admin-random-refresh unified-other-button" type="button" disabled={loading} onClick={()=>void load("",1)}>다른 목회자 보기</button>}</form>
    {error&&<p className="admin-error" role="alert">{error}</p>}
    {selected.size>0&&<div className="admin-batch-bar" role="toolbar" aria-label="선택한 목회자 일괄 처리"><strong>{selected.size}명 선택</strong><button disabled={batchBusy} className="restore" type="button" onClick={()=>void runBatch("approved")}>공개</button><button disabled={batchBusy} type="button" onClick={()=>void runBatch("removed")}>보류</button><button disabled={batchBusy} className="danger" type="button" onClick={()=>void runBatch("deleted")}>삭제</button><button disabled={batchBusy} type="button" onClick={()=>setSelected(new Set(items.map((item)=>item.id)))}>화면 전체 선택</button><button disabled={batchBusy} type="button" onClick={()=>setSelected(new Set())}>선택 해제</button></div>}
    <div className="admin-pastor-manage-list" id="admin-pastor-list" aria-busy={loading}>{items.length?items.map((item)=><PastorDirectoryCard key={item.id} name={item.name.replace(/\s*목사(?:님)?$/u,"")} href={`/pastors/${item.public_id}`} photoUrl={item.photo_url||"/pastor-silhouette-soft.png"} hasPhoto={Boolean(item.photo_url)} roleStatus={item.role_status} roles={[item.role_title??"목회자"]} churchName={item.church_name} churchHref={item.church_id?`/church/${item.church_id}`:null} region={item.region} denomination={item.denomination} sourceUrl={item.source_url} selection={<label className="admin-card-select"><input type="checkbox" checked={selected.has(item.id)} onChange={(event)=>toggleSelected(item.id,event.target.checked)} aria-label={`${item.name} 선택`}/></label>} detail={<div className="admin-pastor-card-state"><span className={`status-${item.review_status}`}>{stateLabel(item.review_status)}</span>{item.photo_url&&<small>사진 {stateLabel(item.photo_review_status)}</small>}</div>} admin editor={{id:item.id,roleId:item.role_id,name:item.name,roleTitle:item.role_title??"목회자",churchName:item.church_name,region:item.region,denomination:item.denomination,roleStatus:item.role_status??"current",status:item.review_status}} useGlobalSelection={false}/>):<p className="admin-empty">{loading?"목회자를 찾고 있습니다.":"검색 결과가 없습니다."}</p>}</div>
    {!appliedQuery&&items.length>0&&<button className="admin-pastor-bottom-refresh unified-other-button" type="button" disabled={loading} onClick={()=>void load("",1)}>다른 목회자 보기</button>}
    {appliedQuery&&pages>1&&<nav className="admin-directory-pagination" aria-label="목회자 검색 페이지"><button type="button" disabled={loading||page<=1} onClick={()=>void load(appliedQuery,page-1)}>이전</button><span>{page}/{pages}</span><button type="button" disabled={loading||page>=pages} onClick={()=>void load(appliedQuery,page+1)}>다음</button></nav>}
  </>;
}
