"use client";
import {useState} from "react";

type Plan={metadata?:{sha256?:string;operation_count?:number;approvalVerified?:boolean};operations?:unknown[]};
export default function ChurchDetailImporter(){
  const [plan,setPlan]=useState<Plan|null>(null),[name,setName]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function choose(file:File|null){setPlan(null);setMessage("");setName(file?.name??"");if(!file)return;try{const value=JSON.parse(await file.text()) as Plan;if(!Array.isArray(value.operations)||!value.metadata?.sha256)throw new Error("검증된 import plan JSON이 아닙니다.");setPlan(value);}catch(reason){setMessage((reason as Error).message)}}
  async function apply(){if(!plan?.metadata?.sha256)return;if(!window.confirm(`${plan.operations?.length??0}건을 운영 데이터에 반영할까요?\n승인 해시 ${plan.metadata.sha256.slice(0,12)}…`))return;setBusy(true);setMessage("");try{const response=await fetch("/api/admin/church-details/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan,confirmedDigest:plan.metadata.sha256})});const result=await response.json() as {error?:string;schedules?:number;profiles?:number};if(!response.ok)throw new Error(result.error||"반영하지 못했습니다.");setMessage(`예배시간 ${result.schedules??0}건, 교회 소개 ${result.profiles??0}건을 반영했습니다.`);setPlan(null);setName("");}catch(reason){setMessage((reason as Error).message)}finally{setBusy(false)}}
  return <section className="admin-panel admin-detail-import"><div className="admin-panel-title"><div><small>REVIEWED DATA IMPORT</small><h2>검토 자료 반영</h2><p>사람 검토와 개인정보 검사를 통과한 import plan만 해시를 다시 확인해 반영합니다.</p></div><span>최대 100건</span></div><label><span>Import plan JSON</span><input type="file" accept="application/json,.json" onChange={(event)=>void choose(event.target.files?.[0]??null)}/></label>{plan&&<div className="admin-import-summary"><strong>{plan.operations?.length??0}건 · {name}</strong><code>{plan.metadata?.sha256}</code><span>{plan.metadata?.approvalVerified?"승인 검증됨":"승인 확인 필요"}</span></div>}<button type="button" disabled={busy||!plan||plan.metadata?.approvalVerified!==true} onClick={()=>void apply()}>{busy?"반영 중…":"검증 자료 반영"}</button>{message&&<p role="status">{message}</p>}</section>;
}
