import type { Metadata } from "next";
import { hasAdminAccess } from "../admin-access";
import { AdminChurchList, ChurchInfoEditControls, ReviewControls, ReviewerAccountControls } from "./admin-controls";
import AdminLogin from "./admin-login";
import AdminListSearch from "./admin-list-search";
import AdminLiveRefresh from "./admin-live-refresh";
import ChurchRequestResolution from "./church-request-resolution";
import { safeHttpUrl } from "../safe-url";
import ReviewerResolutionControls from "./reviewer-resolution-controls";
import HomeReloadLink from "../home-reload-link";
import { database, ensureAnalyticsTables, ensureChurchRecommendationTables, ensureCommunityTables, ensureContactTables, ensureReviewerTables, ensureSermonTables } from "../api/_shared";

export const dynamic = "force-dynamic";
export const metadata:Metadata={title:"관리자 | airChurch",robots:{index:false,follow:false}};

type CountRow = { views: number; visitors: number };
type TimeRow = { period: string; views: number; visitors: number };
type ChurchRow = { id: number; name: string; pastor: string; region: string; denomination: string; review_status: string; hold_reason: string | null; hold_note: string | null; held_at: string | null; priority_weight: number; homepage_url:string|null; youtube_channel_id:string|null; channel_image_url:string|null };
type PostRow = { id: number; category: string; nickname: string; content: string; status: string; created_at: string };
type TalentRow = { id: number; title: string; region: string; description: string; status: string; created_at: string };
type RecommendationRow = { id:number; church_name:string; pastor:string; region:string; denomination:string; youtube_url:string|null; reason:string; status:string; created_at:string };
type ContactRow = { id:number; category:string; name:string; contact:string; message:string; status:string; created_at:string };
type ReviewerAccountRow = { id:number; name:string; contact:string; username:string; status:string; created_at:string };
type ChangeRequestRow={id:number;request_type:string;reason:string;status:string;admin_note:string|null;created_at:string;reviewer_name:string;church_name:string;church_pastor:string;church_region:string;church_denomination:string;church_homepage_url:string|null;church_youtube_channel_id:string|null;proposed_name:string|null;proposed_pastor:string|null;proposed_region:string|null;proposed_denomination:string|null};
type ConcernOpinionRow={id:number;church_id:number;reviewer_name:string;note:string|null;reviewed_at:string;admin_resolution:string|null;admin_note:string|null;church_name:string;church_pastor:string;church_region:string;church_denomination:string;church_homepage_url:string|null;church_youtube_channel_id:string|null;church_status:string;hold_reason:string|null;hold_note:string|null};

async function countSince(db: D1Database, modifier: string): Promise<CountRow> {
  return (await db.prepare("SELECT COUNT(*) AS views, COUNT(DISTINCT visitor_hash) AS visitors FROM page_views WHERE created_at >= datetime('now',?)").bind(modifier).first<CountRow>()) ?? { views: 0, visitors: 0 };
}

function koreanTime(value: string) { return new Date(`${value}Z`).toLocaleString("ko-KR", { timeZone: "Asia/Seoul" }); }
function statusLabel(status: string) { return status === "approved" || status === "published" ? "공개" : status === "pending" ? "검토 중" : status === "removed" ? "보류" : "비공개"; }
function contactStatusLabel(status:string){return status==="approved"?"처리 완료":status==="pending"?"미처리":"처리하지 않음";}
function pastorLabel(name:string){return name.trim().endsWith("목사")?name:`${name} 목사`;}
function ChurchReferenceLinks({name,homepageUrl,youtubeChannelId,channelImageUrl}:{name:string;homepageUrl:string|null;youtubeChannelId:string|null;channelImageUrl?:string|null}){const homepage=safeHttpUrl(homepageUrl),image=safeHttpUrl(channelImageUrl);return <div className="admin-church-reference-links" aria-label={`${name} 확인 링크`}>{homepage&&<a className="admin-homepage-link" href={homepage} target="_blank" rel="noreferrer" aria-label={`${name} 홈페이지 열기`}><span className="homepage-visual" aria-hidden="true"><span>⛪</span>{image&&<img src={image} alt="" loading="lazy" decoding="async" referrerPolicy="no-referrer"/>}</span><b>홈페이지</b></a>}{youtubeChannelId&&<a className="admin-youtube-link" href={`https://www.youtube.com/channel/${youtubeChannelId}`} target="_blank" rel="noreferrer" aria-label={`${name} YouTube 열기`}><span className="directory-icon youtube-icon" aria-hidden="true"/><b>YouTube</b></a>}{!homepage&&!youtubeChannelId&&<span className="admin-reference-empty"><i aria-hidden="true">—</i><b>확인 링크 없음</b></span>}</div>}
function randomChurchIds(rows:ChurchRow[],count:number){const ids=rows.map((row)=>row.id);for(let index=ids.length-1;index>0;index--){const swap=Math.floor(Math.random()*(index+1));[ids[index],ids[swap]]=[ids[swap],ids[index]];}return new Set(ids.slice(0,count));}
function TrafficChart({ rows, label, empty }: { rows: TimeRow[]; label: (period: string) => string; empty: string }) {
  const maxViews = Math.max(1, ...rows.map((row) => Number(row.views)));
  return <div className={`traffic-chart${rows.length > 16 ? " is-dense" : ""}`}>{rows.length ? rows.map((row) => <div className="traffic-day" key={row.period} title={`${row.visitors}명 · ${row.views}회`}><div className="traffic-bar-wrap"><span className="traffic-value">{row.views}</span><div className="traffic-bar" style={{height:`${Math.max(8,Number(row.views)/maxViews*100)}%`}} /></div><small>{label(row.period)}</small></div>) : <p className="admin-empty">{empty}</p>}</div>;
}

export default async function AdminPage() {
  if (!(await hasAdminAccess())) return <AdminLogin />;

  const db = database();
  await Promise.all([ensureAnalyticsTables(db), ensureCommunityTables(db), ensureContactTables(db), ensureSermonTables(db), ensureChurchRecommendationTables(db),ensureReviewerTables(db)]);
  const [today, week, month, active, hourly, daily, monthly, churches, recommendations, churchRows, postRows, talentRows, recommendationRows, contactRows] = await Promise.all([
    db.prepare("SELECT COUNT(*) AS views, COUNT(DISTINCT visitor_hash) AS visitors FROM page_views WHERE created_at >= datetime('now','+9 hours','start of day','-9 hours')").first<CountRow>(),
    countSince(db, "-7 days"), countSince(db, "-30 days"),
    db.prepare("SELECT COUNT(*) AS visitors FROM visitor_activity WHERE last_seen >= datetime('now','-5 minutes')").first<{ visitors: number }>(),
    db.prepare("WITH RECURSIVE hours(period,n) AS (SELECT strftime('%Y-%m-%d %H:00',datetime('now','+9 hours','-23 hours')),0 UNION ALL SELECT strftime('%Y-%m-%d %H:00',datetime(period,'+1 hour')),n+1 FROM hours WHERE n<23) SELECT hours.period,COUNT(page_views.id) AS views,COUNT(DISTINCT page_views.visitor_hash) AS visitors FROM hours LEFT JOIN page_views ON strftime('%Y-%m-%d %H:00',page_views.created_at,'+9 hours')=hours.period GROUP BY hours.period ORDER BY hours.period").all<TimeRow>(),
    db.prepare("WITH RECURSIVE dates(period,n) AS (SELECT date('now','+9 hours','-13 days'),0 UNION ALL SELECT date(period,'+1 day'),n+1 FROM dates WHERE n<13) SELECT dates.period,COUNT(page_views.id) AS views,COUNT(DISTINCT page_views.visitor_hash) AS visitors FROM dates LEFT JOIN page_views ON date(page_views.created_at,'+9 hours')=dates.period GROUP BY dates.period ORDER BY dates.period").all<TimeRow>(),
    db.prepare("WITH RECURSIVE months(period,n) AS (SELECT strftime('%Y-%m',date('now','+9 hours','start of month','-11 months')),0 UNION ALL SELECT strftime('%Y-%m',date(period||'-01','+1 month')),n+1 FROM months WHERE n<11) SELECT months.period,COUNT(page_views.id) AS views,COUNT(DISTINCT page_views.visitor_hash) AS visitors FROM months LEFT JOIN page_views ON strftime('%Y-%m',page_views.created_at,'+9 hours')=months.period GROUP BY months.period ORDER BY months.period").all<TimeRow>(),
    db.prepare("SELECT COUNT(*) AS count FROM churches WHERE review_status='approved'").first<{ count: number }>(),
    db.prepare("SELECT COUNT(*) AS count FROM church_recommendations WHERE status='pending'").first<{ count: number }>(),
    db.prepare("SELECT id,name,pastor,region,denomination,review_status,hold_reason,hold_note,held_at,priority_weight,homepage_url,youtube_channel_id,channel_image_url FROM churches WHERE review_status IN ('approved','removed') ORDER BY CASE review_status WHEN 'approved' THEN 0 ELSE 1 END,priority_weight DESC,name LIMIT 2000").all<ChurchRow>(),
    db.prepare("SELECT id,category,nickname,content,status,created_at FROM community_posts ORDER BY created_at DESC LIMIT 50").all<PostRow>(),
    db.prepare("SELECT id,title,region,description,status,created_at FROM talent_offers ORDER BY created_at DESC LIMIT 50").all<TalentRow>(),
    db.prepare("SELECT id,church_name,pastor,region,denomination,youtube_url,reason,status,created_at FROM church_recommendations ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END,created_at DESC LIMIT 80").all<RecommendationRow>(),
    db.prepare("SELECT id,category,name,contact,message,status,created_at FROM contact_requests ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END,created_at DESC LIMIT 100").all<ContactRow>(),
  ]);
  const publicChurchRows = churchRows.results.filter((church) => church.review_status === "approved");
  const heldChurchRows = churchRows.results.filter((church) => church.review_status === "removed");
  const publicPreviewIds=randomChurchIds(publicChurchRows,20);
  const heldPreviewIds=randomChurchIds(heldChurchRows,10);
  const [reviewerRows,changeRequestRows,pendingConcernRows]=await Promise.all([
    db.prepare("SELECT id,name,contact,username,status,created_at FROM reviewer_accounts ORDER BY CASE status WHEN 'pending' THEN 0 WHEN 'approved' THEN 1 ELSE 2 END,created_at DESC LIMIT 100").all<ReviewerAccountRow>(),
    db.prepare("SELECT r.id,r.request_type,r.reason,r.status,r.admin_note,r.created_at,COALESCE(a.name,'삭제된 계정') AS reviewer_name,c.name AS church_name,c.pastor AS church_pastor,c.region AS church_region,c.denomination AS church_denomination,c.homepage_url AS church_homepage_url,c.youtube_channel_id AS church_youtube_channel_id,r.proposed_name,r.proposed_pastor,r.proposed_region,r.proposed_denomination FROM church_change_requests r JOIN churches c ON c.id=r.church_id LEFT JOIN reviewer_accounts a ON a.id=r.reviewer_id WHERE r.status IN ('pending','deferred') ORDER BY CASE r.status WHEN 'pending' THEN 0 ELSE 1 END,r.created_at ASC LIMIT 1000").all<ChangeRequestRow>(),
    db.prepare("SELECT r.id,r.church_id,COALESCE(a.name,CASE WHEN r.reviewer_id=0 THEN '기본 검토 계정' ELSE '삭제된 계정' END) AS reviewer_name,r.note,r.reviewed_at,r.admin_resolution,r.admin_note,c.name AS church_name,c.pastor AS church_pastor,c.region AS church_region,c.denomination AS church_denomination,c.homepage_url AS church_homepage_url,c.youtube_channel_id AS church_youtube_channel_id,c.review_status AS church_status,c.hold_reason,c.hold_note FROM reviewer_church_reviews r JOIN churches c ON c.id=r.church_id LEFT JOIN reviewer_accounts a ON a.id=r.reviewer_id WHERE r.status='concern' AND r.handled_at IS NULL AND c.review_status IN ('approved','removed') ORDER BY CASE WHEN r.admin_resolution='needs_follow_up' THEN 1 ELSE 0 END,r.reviewed_at ASC LIMIT 1000").all<ConcernOpinionRow>(),
  ]);
  const concernGroups=new Map<number,{church:ConcernOpinionRow;opinions:ConcernOpinionRow[]}>();
  for(const opinion of pendingConcernRows.results){const group=concernGroups.get(opinion.church_id)??{church:opinion,opinions:[]};group.opinions.push(opinion);concernGroups.set(opinion.church_id,group);}
  const pendingConcernGroups=[...concernGroups.values()];
  const pendingRequestCount=changeRequestRows.results.filter((request)=>request.status==="pending").length;
  const pendingReviewerCount=reviewerRows.results.filter((reviewer)=>reviewer.status==="pending").length;
  const pendingContactCount=contactRows.results.filter((request)=>request.status==="pending").length;

  return <main className="admin-shell">
    <AdminLiveRefresh />
    <header className="admin-header">
      <HomeReloadLink className="brand"><span className="brand-mark" aria-hidden="true" /><span>airchurch</span></HomeReloadLink><div><span>관리자</span><a href="/pastor">목사님 페이지</a><form action="/api/admin/lock" method="post"><button type="submit">로그아웃</button></form></div>
    </header>
    <section className="admin-title"><div><span>ADMIN ACTION CENTER</span><h1>오늘 처리할 운영 업무</h1><p>목사님이 확인을 요청한 교회부터 결정하고, 나머지 운영 현황은 아래에서 확인하세요.</p></div>
      <HomeReloadLink>사이트 보기 ↗</HomeReloadLink>
    </section>
    <section className="admin-operations action-center-cards"><a className="admin-operation-card opinion" href="#reviewer-queue"><small>목사님 요청</small><strong>{changeRequestRows.results.length+pendingConcernGroups.length}</strong><span>{pendingRequestCount||pendingConcernGroups.length?`처리할 요청 ${pendingRequestCount+pendingConcernGroups.length}건 ↓`:"새 요청 없음"}</span></a><a className="admin-operation-card" href="#contact-requests"><small>운영 문의</small><strong>{pendingContactCount}</strong><span>권리자·정보 수정 요청 확인 ↓</span></a><a className="admin-operation-card" href="#reviewer-accounts"><small>가입 승인 대기</small><strong>{pendingReviewerCount}</strong><span>목회자 계정 확인 ↓</span></a><a className="admin-operation-card" href="#church-recommendations"><small>교회 추천 검토</small><strong>{recommendations?.count ?? 0}</strong><span>등록 결정 ↓</span></a><a className="admin-operation-card" href="#church-management"><small>전체 교회</small><strong>{churches?.count ?? 0}</strong><span>검색·수정·보류·삭제 ↓</span></a></section>

    <section className="admin-panel reviewer-queue" id="reviewer-queue"><div className="admin-panel-title"><div><small>PASTOR REQUESTS</small><h2>목사님 요청 결정</h2><p>요청 내용을 그대로 승인하거나, 반려해 목사님이 다시 보게 하거나, 일단 보류만 결정합니다.</p></div><span>{changeRequestRows.results.length}건</span></div><div className="reviewer-queue-list">{changeRequestRows.results.length?changeRequestRows.results.map((request)=><article className="is-concern" key={request.id}><div className="admin-record-heading"><div><strong>{request.church_name}</strong><small><b>{pastorLabel(request.church_pastor)}</b> · {request.church_region} · {request.church_denomination}</small></div><div className="admin-record-status"><span className="reviewer-concern">{request.request_type==="edit"?"수정 요청":request.request_type==="hold"?"보류 요청":"삭제 요청"}</span><span>{request.reviewer_name}</span></div></div><ChurchReferenceLinks name={request.church_name} homepageUrl={request.church_homepage_url} youtubeChannelId={request.church_youtube_channel_id}/><div className="reviewer-opinion-copy"><time>{koreanTime(request.created_at)}</time><p>{request.reason}</p>{request.request_type==="edit"&&<p><strong>변경안</strong> · {request.proposed_name} · {request.proposed_pastor} · {request.proposed_region} · {request.proposed_denomination}</p>}{request.status==="deferred"&&request.admin_note&&<p className="admin-follow-up-note">일단 보류 · {request.admin_note}</p>}</div><ChurchRequestResolution id={request.id}/></article>):<div className="reviewer-queue-empty"><strong>지금 처리할 목사님 요청이 없습니다</strong><p>새 요청이 접수되면 이곳에 표시됩니다.</p></div>}</div></section>

    {pendingConcernGroups.length>0&&<section className="admin-panel reviewer-queue"><div className="admin-panel-title"><div><small>REPORTED PROBLEMS</small><h2>문제가 제보된 교회</h2><p>미검토 교회는 표시하지 않습니다. 접수된 문제만 확인해 공개·보류·재검토·삭제를 결정합니다.</p></div><span>{pendingConcernGroups.length}곳</span></div><div className="reviewer-queue-list">{pendingConcernGroups.map(({church,opinions})=><article className="is-concern" key={church.church_id}><div className="admin-record-heading"><div><strong>{church.church_name}</strong><small><b>{pastorLabel(church.church_pastor)}</b> · {church.church_region} · {church.church_denomination}</small></div><div className="admin-record-status"><span className="reviewer-concern">문제 제보 {opinions.length}건</span><span className={`status-${church.church_status}`}>{statusLabel(church.church_status)}</span></div></div><ChurchReferenceLinks name={church.church_name} homepageUrl={church.church_homepage_url} youtubeChannelId={church.church_youtube_channel_id}/><ChurchInfoEditControls id={church.church_id} name={church.church_name} pastor={church.church_pastor} region={church.church_region} denomination={church.church_denomination}/><div className="reviewer-opinion-list">{opinions.map((opinion)=><div className="reviewer-opinion-copy" key={opinion.id}><strong>{opinion.reviewer_name}</strong><time>{koreanTime(opinion.reviewed_at)}</time><p>{opinion.note||"확인이 필요한 교회로 제보했습니다."}</p></div>)}</div><ReviewerResolutionControls churchId={church.church_id} churchStatus={church.church_status} opinions={opinions.map((opinion)=>({id:opinion.id,reviewedAt:opinion.reviewed_at}))} existingNote={opinions.find((opinion)=>opinion.admin_note)?.admin_note} existingHoldReason={church.hold_reason} existingHoldNote={church.hold_note}/></article>)}</div></section>}

    <section className="admin-section-heading" id="site-analytics"><span>SITE STATUS</span><h2>사이트 현황</h2><p>방문 흐름을 확인합니다.</p></section>
    <section className="admin-metrics">
      <article className="active-visitors"><small>현재 접속자</small><strong>{Number(active?.visitors ?? 0).toLocaleString("ko-KR")}</strong><span>최근 5분 안에 활동한 방문자</span></article>
      <article><small>오늘 방문자</small><strong>{Number(today?.visitors ?? 0).toLocaleString("ko-KR")}</strong><span>{Number(today?.views ?? 0).toLocaleString("ko-KR")}회 조회</span></article>
      <article><small>최근 7일 방문자</small><strong>{Number(week.visitors).toLocaleString("ko-KR")}</strong><span>{Number(week.views).toLocaleString("ko-KR")}회 조회</span></article>
      <article><small>최근 30일 방문자</small><strong>{Number(month.visitors).toLocaleString("ko-KR")}</strong><span>{Number(month.views).toLocaleString("ko-KR")}회 조회</span></article>
    </section>
    <section className="admin-grid analytics-grid">
      <article className="admin-panel analytics-wide"><div className="admin-panel-title"><div><small>최근 14일</small><h2>날짜별 방문</h2></div><span>빠진 날짜 없이 조회수 표시 · 막대에 올리면 방문자 표시</span></div><TrafficChart rows={daily.results} label={(period)=>`${Number(period.slice(5,7))}/${Number(period.slice(8,10))}`} empty="방문 기록이 없습니다." /></article>
      <article className="admin-panel"><div className="admin-panel-title"><div><small>최근 24시간</small><h2>시간별 방문</h2></div><span>빠진 시간 없이 표시</span></div><TrafficChart rows={hourly.results} label={(period)=>`${Number(period.slice(11,13))}시`} empty="방문 기록이 없습니다." /></article>
      <article className="admin-panel"><div className="admin-panel-title"><div><small>최근 12개월</small><h2>월별 방문</h2></div><span>빠진 달 없이 표시</span></div><TrafficChart rows={monthly.results} label={(period)=>`${Number(period.slice(5))}월`} empty="방문 기록이 없습니다." /></article>
    </section>

    <section className="admin-management-grid">
      <article className="admin-panel" id="church-management"><div className="admin-panel-title"><div><small>CHURCH MANAGEMENT</small><h2>전체 교회 관리</h2><p>처음에는 무작위 20곳만 표시합니다. 검색하면 전체 교회에서 일치하는 결과를 보여줍니다.</p></div><span>{publicChurchRows.length}곳</span></div><AdminListSearch targetId="public-church-list" total={publicChurchRows.length} label="공개 교회 검색" placeholder="교회명, 목사님, 지역, 교단 검색" initialLimit={20}/><div className="admin-manage-list" id="public-church-list">{publicChurchRows.length ? <AdminChurchList churches={publicChurchRows} previewIds={[...publicPreviewIds]} variant="public"/> : <p className="admin-empty">공개 중인 교회가 없습니다.</p>}</div></article>
      <article className="admin-panel" id="church-hold"><div className="admin-panel-title"><div><small>CHURCH HOLD</small><h2>보류 교회</h2><p>처음에는 무작위 10곳만 표시합니다. 검색하면 전체 보류 교회에서 일치하는 결과를 보여줍니다.</p></div><span>{heldChurchRows.length}곳</span></div><AdminListSearch targetId="held-church-list" total={heldChurchRows.length} label="보류 교회 검색" placeholder="교회명, 목사님, 지역, 보류 메모 검색" initialLimit={10}/><div className="admin-manage-list" id="held-church-list">{heldChurchRows.length ? <AdminChurchList churches={heldChurchRows} previewIds={[...heldPreviewIds]} variant="held"/> : <p className="admin-empty">보류된 교회가 없습니다.</p>}</div></article>
    </section>

    <section className="admin-review-grid">
      <article className="admin-panel" id="contact-requests"><div className="admin-panel-title"><div><small>CONTACT REQUESTS</small><h2>운영 문의</h2><p>권리자 비공개 요청과 정보 수정 요청을 먼저 확인합니다.</p></div><span>{contactRows.results.length}건</span></div><div className="review-list">{contactRows.results.length?contactRows.results.map((item)=><article key={item.id}><div><span>{item.category} · {contactStatusLabel(item.status)}</span><time>{koreanTime(item.created_at)}</time></div><strong>{item.name}</strong><p>{item.contact}</p><p>{item.message}</p><ReviewControls kind="contact" id={item.id} status={item.status}/></article>):<p className="admin-empty">접수된 운영 문의가 없습니다.</p>}</div></article>
      <article className="admin-panel" id="reviewer-accounts"><div className="admin-panel-title"><div><small>REVIEWER ACCOUNTS</small><h2>목회자 검토 참여 신청</h2><p>성함과 연락처를 확인한 뒤 교회 검토 참여를 승인해 주세요.</p></div><span>{reviewerRows.results.length}명</span></div><div className="review-list">{reviewerRows.results.length?reviewerRows.results.map((item)=><article key={item.id}><div><span>{statusLabel(item.status)}</span><time>{koreanTime(item.created_at)}</time></div><strong>{item.name} · {item.username}</strong><p>{item.contact}</p><ReviewerAccountControls id={item.id} status={item.status}/></article>):<p className="admin-empty">목회자 참여 신청이 없습니다.</p>}</div></article>
      <article className="admin-panel" id="church-recommendations"><div className="admin-panel-title"><div><small>CHURCH RECOMMENDATIONS</small><h2>교회 추천 검토</h2><p>교단 소속과 공식 채널을 직접 확인한 뒤 등록을 승인해 주세요.</p></div><span>{recommendationRows.results.length}건</span></div><div className="review-list">{recommendationRows.results.length?recommendationRows.results.map((item)=><article key={item.id}><div><span>{item.region} · {statusLabel(item.status)}</span><time>{koreanTime(item.created_at)}</time></div><strong>{item.church_name} · {item.pastor}</strong><p>{item.denomination}</p><p>{item.reason}</p>{item.youtube_url?<a className="admin-review-link" href={item.youtube_url} target="_blank" rel="noreferrer">공식 YouTube 확인 ↗</a>:<span className="admin-reference-missing">등록된 확인 링크 없음</span>}<ReviewControls kind="recommendation" id={item.id} status={item.status}/></article>):<p className="admin-empty">접수된 교회 추천이 없습니다.</p>}</div></article>
      <article className="admin-panel" id="pending-posts"><div className="admin-panel-title"><div><small>COMMUNITY REVIEW</small><h2>익명 글 관리</h2></div><span>{postRows.results.length}건</span></div><div className="review-list">{postRows.results.length ? postRows.results.map((post) => <article key={post.id}><div><span>{post.category} · {statusLabel(post.status)}</span><time>{koreanTime(post.created_at)}</time></div><strong>{post.nickname}</strong><p>{post.content}</p><ReviewControls kind="post" id={post.id} status={post.status} /></article>) : <p className="admin-empty">접수된 익명 글이 없습니다.</p>}</div></article>
      <article className="admin-panel" id="pending-talents"><div className="admin-panel-title"><div><small>TALENT REVIEW</small><h2>달란트 관리</h2></div><span>{talentRows.results.length}건</span></div><div className="review-list">{talentRows.results.length ? talentRows.results.map((talent) => <article key={talent.id}><div><span>{talent.region} · {statusLabel(talent.status)}</span><time>{koreanTime(talent.created_at)}</time></div><strong>{talent.title}</strong><p>{talent.description}</p><ReviewControls kind="talent" id={talent.id} status={talent.status} /></article>) : <p className="admin-empty">접수된 달란트가 없습니다.</p>}</div></article>
    </section>
    <p className="admin-privacy">현재 접속자는 1분마다 자동 갱신됩니다. IP 주소, 이름, 이메일은 방문 통계에 저장하지 않습니다. 동일 브라우저의 익명 식별값은 해시 처리하고 같은 페이지의 30분 이내 중복 조회는 제외합니다.</p>
  </main>;
}
