import type { Metadata } from "next";
import { hasAdminAccess } from "../admin-access";
import { ChurchInfoEditControls, ReviewControls, ReviewerAccountControls } from "./admin-controls";
import AdminChurchDirectory from "./admin-church-directory";
import AdminLogin from "./admin-login";
import AdminLiveRefresh from "./admin-live-refresh";
import ChurchRequestResolution from "./church-request-resolution";
import { safeHttpUrl } from "../safe-url";
import ReviewerResolutionControls from "./reviewer-resolution-controls";
import HomeReloadLink from "../home-reload-link";
import { database, ensureAdminTables } from "../api/_shared";
import PrivateContactList from "../private-contact-list";
import { readPrivateContacts } from "../private-contact-vault";
import ChurchDetailImporter from "./church-detail-importer";

export const dynamic = "force-dynamic";
export const metadata:Metadata={title:"관리자 | airChurch",robots:{index:false,follow:false}};

type CountRow = { views: number; visitors: number };
type TimeRow = { period: string; views: number; visitors: number };
type ChurchRow = { id: number; name: string; pastor: string; region: string; denomination: string; review_status: string; hold_reason: string | null; hold_note: string | null; held_at: string | null; priority_weight: number; homepage_url:string|null; youtube_channel_id:string|null; channel_image_url:string|null };
type PostRow = { id: number; category: string; nickname: string; content: string; status: string; report_count:number; created_at: string };
type TalentRow = { id: number; title: string; region: string; description: string; status: string; created_at: string };
type RecommendationRow = { id:number; church_name:string; pastor:string; region:string; denomination:string; youtube_url:string|null; reason:string; status:string; created_at:string };
type ContactRow = { id:number; category:string; name:string; contact:string; message:string; status:string; created_at:string };
type ReviewerAccountRow = { id:number; name:string; contact:string; username:string; status:string; created_at:string };
type ChangeRequestRow={id:number;request_type:string;reason:string;status:string;admin_note:string|null;created_at:string;reviewer_name:string;church_name:string;church_pastor:string;church_region:string;church_denomination:string;church_homepage_url:string|null;church_youtube_channel_id:string|null;proposed_name:string|null;proposed_pastor:string|null;proposed_region:string|null;proposed_denomination:string|null};
type ConcernOpinionRow={id:number;church_id:number;reviewer_name:string;note:string|null;reviewed_at:string;admin_resolution:string|null;admin_note:string|null;church_name:string;church_pastor:string;church_region:string;church_denomination:string;church_homepage_url:string|null;church_youtube_channel_id:string|null;church_status:string;hold_reason:string|null;hold_note:string|null};
type MediaFreshnessRow={sermon_at:string|null;praise_at:string|null;short_at:string|null;sermon_sync_at:string|null;praise_sync_at:string|null;retention_at:string|null;now_epoch:string|null};
type ChurchStatusEventRow={id:number;church_id:number;church_name:string;previous_status:string|null;new_status:string;reason:string|null;created_at:string};
type EncouragementAdminRow={id:number;target_type:string;nickname:string;content:string;status:string;created_at:string;church_id:number;church_name:string;pastor:string};
type MinistrySuggestionRow={id:number;church_id:number;name:string;role_title:string;source_url:string|null;note:string;status:string;created_at:string;church_name:string};

async function countSince(db: D1Database, modifier: string): Promise<CountRow> {
  return (await db.prepare("SELECT COUNT(*) AS views, COUNT(DISTINCT visitor_hash) AS visitors FROM page_views WHERE created_at >= datetime('now',?)").bind(modifier).first<CountRow>()) ?? { views: 0, visitors: 0 };
}

function koreanTime(value: string) { return new Date(`${value}Z`).toLocaleString("ko-KR", { timeZone: "Asia/Seoul" }); }
function statusLabel(status: string) { return status === "approved" || status === "published" ? "공개" : status === "pending" ? "검토 중" : status === "removed" ? "보류" : "비공개"; }
function contactStatusLabel(status:string){return status==="approved"?"처리 완료":status==="pending"?"미처리":"처리하지 않음";}
function statusReasonLabel(reason:string|null){return reason==="registration"?"새 교회 등록":reason==="pastor_request"?"목회자 요청":reason==="rights_request"?"저작권·개인정보·권리자 요청":reason==="youtube_unavailable"?"공식 YouTube 확인 불가":reason==="inactive"?"최근 설교 확인 불가":reason==="info_unverified"?"교회 정보 재확인":reason==="review_needed"?"운영상 재검토":reason==="status_change"?"공개 상태 변경":reason||"상태 변경";}
function pastorLabel(name:string){return name.trim().endsWith("목사")?name:`${name} 목사`;}
function ChurchReferenceLinks({name,homepageUrl,youtubeChannelId,channelImageUrl}:{name:string;homepageUrl:string|null;youtubeChannelId:string|null;channelImageUrl?:string|null}){const homepage=safeHttpUrl(homepageUrl),image=safeHttpUrl(channelImageUrl);return <div className="admin-church-reference-links" aria-label={`${name} 확인 링크`}>{homepage&&<a className="admin-homepage-link" href={homepage} target="_blank" rel="noreferrer" aria-label={`${name} 홈페이지 열기`}><span className="homepage-visual" aria-hidden="true"><span>⛪</span>{image&&<img src={image} alt="" loading="lazy" decoding="async" referrerPolicy="no-referrer"/>}</span><b>홈페이지</b></a>}{youtubeChannelId&&<a className="admin-youtube-link" href={`https://www.youtube.com/channel/${youtubeChannelId}`} target="_blank" rel="noreferrer" aria-label={`${name} YouTube 열기`}><span className="directory-icon youtube-icon" aria-hidden="true"/><b>YouTube</b></a>}{!homepage&&!youtubeChannelId&&<span className="admin-reference-empty"><i aria-hidden="true">—</i><b>확인 링크 없음</b></span>}</div>}
function TrafficChart({ rows, label, empty }: { rows: TimeRow[]; label: (period: string) => string; empty: string }) {
  const maxViews = Math.max(1, ...rows.map((row) => Number(row.views)));
  return <div className={`traffic-chart${rows.length > 16 ? " is-dense" : ""}`}>{rows.length ? rows.map((row) => <div className="traffic-day" key={row.period} title={`${row.visitors}명 · ${row.views}회`}><div className="traffic-bar-wrap"><span className="traffic-value">{row.views}</span><div className="traffic-bar" style={{height:`${Math.max(8,Number(row.views)/maxViews*100)}%`}} /></div><small>{label(row.period)}</small></div>) : <p className="admin-empty">{empty}</p>}</div>;
}

export default async function AdminPage() {
  if (!(await hasAdminAccess())) return <AdminLogin />;

  const db = database();
  await ensureAdminTables(db);
  const privateContacts=await readPrivateContacts(db,{role:"admin",reviewerId:0});
  const [today, week, month, active, hourly, daily, monthly, churches, heldChurches, recommendations, pendingCommunity, publicChurchRows, heldChurchRows, postRows, talentRows, recommendationRows, contactRows] = await Promise.all([
    db.prepare("SELECT COUNT(*) AS views, COUNT(DISTINCT visitor_hash) AS visitors FROM page_views WHERE created_at >= datetime('now','+9 hours','start of day','-9 hours')").first<CountRow>(),
    countSince(db, "-7 days"), countSince(db, "-30 days"),
    db.prepare("SELECT COUNT(*) AS visitors FROM visitor_activity WHERE last_seen >= datetime('now','-5 minutes')").first<{ visitors: number }>(),
    db.prepare("WITH RECURSIVE hours(period,n) AS (SELECT strftime('%Y-%m-%d %H:00',datetime('now','+9 hours','-23 hours')),0 UNION ALL SELECT strftime('%Y-%m-%d %H:00',datetime(period,'+1 hour')),n+1 FROM hours WHERE n<23) SELECT hours.period,COUNT(page_views.id) AS views,COUNT(DISTINCT page_views.visitor_hash) AS visitors FROM hours LEFT JOIN page_views ON strftime('%Y-%m-%d %H:00',page_views.created_at,'+9 hours')=hours.period GROUP BY hours.period ORDER BY hours.period").all<TimeRow>(),
    db.prepare("WITH RECURSIVE dates(period,n) AS (SELECT date('now','+9 hours','-13 days'),0 UNION ALL SELECT date(period,'+1 day'),n+1 FROM dates WHERE n<13) SELECT dates.period,COUNT(page_views.id) AS views,COUNT(DISTINCT page_views.visitor_hash) AS visitors FROM dates LEFT JOIN page_views ON date(page_views.created_at,'+9 hours')=dates.period GROUP BY dates.period ORDER BY dates.period").all<TimeRow>(),
    db.prepare("WITH RECURSIVE months(period,n) AS (SELECT strftime('%Y-%m',date('now','+9 hours','start of month','-11 months')),0 UNION ALL SELECT strftime('%Y-%m',date(period||'-01','+1 month')),n+1 FROM months WHERE n<11) SELECT months.period,COUNT(page_views.id) AS views,COUNT(DISTINCT page_views.visitor_hash) AS visitors FROM months LEFT JOIN page_views ON strftime('%Y-%m',page_views.created_at,'+9 hours')=months.period GROUP BY months.period ORDER BY months.period").all<TimeRow>(),
    db.prepare("SELECT COUNT(*) AS count FROM churches WHERE review_status='approved'").first<{ count: number }>(),
    db.prepare("SELECT COUNT(*) AS count FROM churches WHERE review_status='removed'").first<{ count: number }>(),
    db.prepare("SELECT COUNT(*) AS count FROM church_recommendations WHERE status='pending'").first<{ count: number }>(),
    db.prepare("SELECT COUNT(*) AS count FROM community_posts WHERE status='pending'").first<{ count: number }>(),
    db.prepare("SELECT id,name,pastor,region,denomination,review_status,hold_reason,hold_note,held_at,priority_weight,homepage_url,youtube_channel_id,channel_image_url FROM churches WHERE review_status='approved' ORDER BY RANDOM() LIMIT 20").all<ChurchRow>(),
    db.prepare("SELECT id,name,pastor,region,denomination,review_status,hold_reason,hold_note,held_at,priority_weight,homepage_url,youtube_channel_id,channel_image_url FROM churches WHERE review_status='removed' ORDER BY RANDOM() LIMIT 10").all<ChurchRow>(),
    db.prepare("SELECT id,category,nickname,content,status,report_count,created_at FROM community_posts ORDER BY CASE WHEN report_count>=3 THEN 0 ELSE 1 END,created_at DESC LIMIT 50").all<PostRow>(),
    db.prepare("SELECT id,title,region,description,status,created_at FROM talent_offers ORDER BY created_at DESC LIMIT 50").all<TalentRow>(),
    db.prepare("SELECT id,church_name,pastor,region,denomination,youtube_url,reason,status,created_at FROM church_recommendations ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END,created_at DESC LIMIT 80").all<RecommendationRow>(),
    db.prepare("SELECT id,category,name,contact,message,status,created_at FROM contact_requests ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END,created_at DESC LIMIT 100").all<ContactRow>(),
  ]);
  const [reviewerRows,changeRequestRows,pendingConcernRows,encouragementRows,ministrySuggestionRows]=await Promise.all([
    db.prepare("SELECT id,name,contact,username,status,created_at FROM reviewer_accounts ORDER BY CASE status WHEN 'pending' THEN 0 WHEN 'approved' THEN 1 ELSE 2 END,created_at DESC LIMIT 100").all<ReviewerAccountRow>(),
    db.prepare("SELECT r.id,r.request_type,r.reason,r.status,r.admin_note,r.created_at,COALESCE(a.name,'삭제된 계정') AS reviewer_name,c.name AS church_name,c.pastor AS church_pastor,c.region AS church_region,c.denomination AS church_denomination,c.homepage_url AS church_homepage_url,c.youtube_channel_id AS church_youtube_channel_id,r.proposed_name,r.proposed_pastor,r.proposed_region,r.proposed_denomination FROM church_change_requests r JOIN churches c ON c.id=r.church_id LEFT JOIN reviewer_accounts a ON a.id=r.reviewer_id WHERE r.status IN ('pending','deferred') ORDER BY CASE r.status WHEN 'pending' THEN 0 ELSE 1 END,r.created_at ASC LIMIT 1000").all<ChangeRequestRow>(),
    db.prepare("SELECT r.id,r.church_id,COALESCE(a.name,CASE WHEN r.reviewer_id=0 THEN '기본 검토 계정' ELSE '삭제된 계정' END) AS reviewer_name,r.note,r.reviewed_at,r.admin_resolution,r.admin_note,c.name AS church_name,c.pastor AS church_pastor,c.region AS church_region,c.denomination AS church_denomination,c.homepage_url AS church_homepage_url,c.youtube_channel_id AS church_youtube_channel_id,c.review_status AS church_status,c.hold_reason,c.hold_note FROM reviewer_church_reviews r JOIN churches c ON c.id=r.church_id LEFT JOIN reviewer_accounts a ON a.id=r.reviewer_id WHERE r.status='concern' AND r.handled_at IS NULL AND c.review_status IN ('approved','removed') ORDER BY CASE WHEN r.admin_resolution='needs_follow_up' THEN 1 ELSE 0 END,r.reviewed_at ASC LIMIT 1000").all<ConcernOpinionRow>(),
    db.prepare("SELECT e.id,e.target_type,e.nickname,e.content,e.status,e.created_at,e.church_id,c.name AS church_name,c.pastor FROM encouragement_messages e JOIN churches c ON c.id=e.church_id ORDER BY e.created_at DESC,e.id DESC").all<EncouragementAdminRow>(),
    db.prepare("SELECT s.id,s.church_id,s.name,s.role_title,s.source_url,s.note,s.status,s.created_at,c.name AS church_name FROM ministry_profile_suggestions s JOIN churches c ON c.id=s.church_id ORDER BY CASE s.status WHEN 'pending' THEN 0 ELSE 1 END,s.created_at DESC LIMIT 200").all<MinistrySuggestionRow>(),
  ]);
  const concernGroups=new Map<number,{church:ConcernOpinionRow;opinions:ConcernOpinionRow[]}>();
  for(const opinion of pendingConcernRows.results){const group=concernGroups.get(opinion.church_id)??{church:opinion,opinions:[]};group.opinions.push(opinion);concernGroups.set(opinion.church_id,group);}
  const pendingConcernGroups=[...concernGroups.values()];
  const pendingRequestCount=changeRequestRows.results.filter((request)=>request.status==="pending").length;
  const pendingReviewerCount=reviewerRows.results.filter((reviewer)=>reviewer.status==="pending").length;
  const pendingContactCount=contactRows.results.filter((request)=>request.status==="pending").length;
  const [mediaFreshness,statusEvents]=await Promise.all([
    db.prepare("SELECT (SELECT MAX(published_at) FROM sermons WHERE status='published') AS sermon_at,(SELECT MAX(published_at) FROM praise_videos WHERE status='published') AS praise_at,(SELECT MAX(published_at) FROM church_shorts WHERE status='published') AS short_at,COALESCE((SELECT last_synced_at FROM sync_state WHERE key='youtube-sermon-last-success'),(SELECT last_synced_at FROM sync_state WHERE key='youtube-v9-regional-130')) AS sermon_sync_at,COALESCE((SELECT last_synced_at FROM sync_state WHERE key='youtube-praise-last-success'),(SELECT last_synced_at FROM sync_state WHERE key='youtube-praise-v1')) AS praise_sync_at,(SELECT completed_at FROM maintenance_state WHERE key='personal-data-retention-v1') AS retention_at,strftime('%s','now') AS now_epoch").first<MediaFreshnessRow>(),
    db.prepare("SELECT id,church_id,church_name,previous_status,new_status,reason,created_at FROM church_status_events ORDER BY created_at DESC,id DESC LIMIT 8").all<ChurchStatusEventRow>(),
  ]);
  const freshnessLabel=(value:string|null|undefined)=>value?new Date(value.endsWith("Z")?value:`${value}Z`).toLocaleString("ko-KR",{timeZone:"Asia/Seoul",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}):"기록 없음";
  const utcEpoch=(value:string|null|undefined)=>value?Date.parse(value.endsWith("Z")?value:`${value}Z`)/1000:NaN;
  const sermonSyncEpoch=utcEpoch(mediaFreshness?.sermon_sync_at),praiseSyncEpoch=utcEpoch(mediaFreshness?.praise_sync_at);
  const retentionEpoch=utcEpoch(mediaFreshness?.retention_at);
  const nowEpoch=mediaFreshness?.now_epoch ? Number(mediaFreshness.now_epoch) : NaN;
  const sermonSyncHealthy=Number.isFinite(sermonSyncEpoch)&&Number.isFinite(nowEpoch)&&nowEpoch-sermonSyncEpoch<12*60*60;
  const praiseSyncHealthy=Number.isFinite(praiseSyncEpoch)&&Number.isFinite(nowEpoch)&&nowEpoch-praiseSyncEpoch<12*60*60;
  const retentionHealthy=Number.isFinite(retentionEpoch)&&Number.isFinite(nowEpoch)&&nowEpoch-retentionEpoch<36*60*60;
  const safeChurchRows=(rows:ChurchRow[])=>rows.map((church)=>({...church,homepage_url:safeHttpUrl(church.homepage_url),channel_image_url:safeHttpUrl(church.channel_image_url)}));

  return <main className="admin-shell">
    <AdminLiveRefresh />
    <header className="admin-header">
      <HomeReloadLink className="brand"><span className="brand-mark" aria-hidden="true" /><span>airchurch</span></HomeReloadLink><div><span>관리자</span><a href="/pastor">목사님 페이지</a><form action="/api/admin/lock" method="post"><button type="submit">로그아웃</button></form></div>
    </header>
    <section className="admin-title"><div><span>ADMIN ACTION CENTER</span><h1>오늘 처리할 운영 업무</h1><p>목사님이 확인을 요청한 교회부터 결정하고, 나머지 운영 현황은 아래에서 확인하세요.</p></div>
      <HomeReloadLink>사이트 보기 ↗</HomeReloadLink>
    </section>
    <section className="admin-operations action-center-cards"><a className="admin-operation-card opinion" href="#reviewer-queue"><small>목사님 요청</small><strong>{changeRequestRows.results.length+pendingConcernGroups.length}</strong><span>{pendingRequestCount||pendingConcernGroups.length?`처리할 요청 ${pendingRequestCount+pendingConcernGroups.length}건 ↓`:"새 요청 없음"}</span></a><a className="admin-operation-card" href="#ministry-suggestions"><small>교역자 제보</small><strong>{ministrySuggestionRows.results.filter((item)=>item.status==="pending").length}</strong><span>공식 출처 확인 후 반영 ↓</span></a><a className="admin-operation-card" href="#encouragement-messages"><small>응원글 전체</small><strong>{encouragementRows.results.length}</strong><span>교회·목사 응원글 관리 ↓</span></a><a className="admin-operation-card" href="#contact-requests"><small>운영 문의</small><strong>{pendingContactCount}</strong><span>권리자·정보 수정 요청 확인 ↓</span></a><a className="admin-operation-card" href="#pending-posts"><small>익명 글 검토</small><strong>{pendingCommunity?.count??0}</strong><span>새 글·신고 누적 글 결정 ↓</span></a><a className="admin-operation-card" href="#reviewer-accounts"><small>가입 승인 대기</small><strong>{pendingReviewerCount}</strong><span>목회자 계정 확인 ↓</span></a><a className="admin-operation-card" href="#church-recommendations"><small>교회 추천 검토</small><strong>{recommendations?.count ?? 0}</strong><span>등록 결정 ↓</span></a><a className="admin-operation-card" href="#church-management"><small>전체 교회</small><strong>{churches?.count ?? 0}</strong><span>검색·수정·보류·삭제 ↓</span></a></section>

    <PrivateContactList items={privateContacts} viewer="관리자"/>

    <section className="admin-panel reviewer-queue" id="reviewer-queue"><div className="admin-panel-title"><div><small>PASTOR REQUESTS</small><h2>목사님 요청 결정</h2><p>요청 내용을 그대로 승인하거나, 반려해 목사님이 다시 보게 하거나, 일단 보류만 결정합니다.</p></div><span>{changeRequestRows.results.length}건</span></div><div className="reviewer-queue-list">{changeRequestRows.results.length?changeRequestRows.results.map((request)=><article className="is-concern" key={request.id}><div className="admin-record-heading"><div><strong>{request.church_name}</strong><small><b>{pastorLabel(request.church_pastor)}</b> · {request.church_region} · {request.church_denomination}</small></div><div className="admin-record-status"><span className="reviewer-concern">{request.request_type==="edit"?"수정 요청":request.request_type==="hold"?"보류 요청":"삭제 요청"}</span><span>{request.reviewer_name}</span></div></div><ChurchReferenceLinks name={request.church_name} homepageUrl={request.church_homepage_url} youtubeChannelId={request.church_youtube_channel_id}/><div className="reviewer-opinion-copy"><time>{koreanTime(request.created_at)}</time><p>{request.reason}</p>{request.request_type==="edit"&&<p><strong>변경안</strong> · {request.proposed_name} · {request.proposed_pastor} · {request.proposed_region} · {request.proposed_denomination}</p>}{request.status==="deferred"&&request.admin_note&&<p className="admin-follow-up-note">일단 보류 · {request.admin_note}</p>}</div><ChurchRequestResolution id={request.id}/></article>):<div className="reviewer-queue-empty"><strong>지금 처리할 목사님 요청이 없습니다</strong><p>새 요청이 접수되면 이곳에 표시됩니다.</p></div>}</div></section>

    {pendingConcernGroups.length>0&&<section className="admin-panel reviewer-queue"><div className="admin-panel-title"><div><small>REPORTED PROBLEMS</small><h2>문제가 제보된 교회</h2><p>미검토 교회는 표시하지 않습니다. 접수된 문제만 확인해 공개·보류·재검토·삭제를 결정합니다.</p></div><span>{pendingConcernGroups.length}곳</span></div><div className="reviewer-queue-list">{pendingConcernGroups.map(({church,opinions})=><article className="is-concern" key={church.church_id}><div className="admin-record-heading"><div><strong>{church.church_name}</strong><small><b>{pastorLabel(church.church_pastor)}</b> · {church.church_region} · {church.church_denomination}</small></div><div className="admin-record-status"><span className="reviewer-concern">문제 제보 {opinions.length}건</span><span className={`status-${church.church_status}`}>{statusLabel(church.church_status)}</span></div></div><ChurchReferenceLinks name={church.church_name} homepageUrl={church.church_homepage_url} youtubeChannelId={church.church_youtube_channel_id}/><ChurchInfoEditControls id={church.church_id} name={church.church_name} pastor={church.church_pastor} region={church.church_region} denomination={church.church_denomination}/><div className="reviewer-opinion-list">{opinions.map((opinion)=><div className="reviewer-opinion-copy" key={opinion.id}><strong>{opinion.reviewer_name}</strong><time>{koreanTime(opinion.reviewed_at)}</time><p>{opinion.note||"확인이 필요한 교회로 제보했습니다."}</p></div>)}</div><ReviewerResolutionControls churchId={church.church_id} churchStatus={church.church_status} opinions={opinions.map((opinion)=>({id:opinion.id,reviewedAt:opinion.reviewed_at}))} existingNote={opinions.find((opinion)=>opinion.admin_note)?.admin_note} existingHoldReason={church.hold_reason} existingHoldNote={church.hold_note}/></article>)}</div></section>}

    <section className="admin-section-heading" id="site-analytics"><span>SITE STATUS</span><h2>사이트 현황</h2><p>방문 흐름을 확인합니다.</p></section>
    <section className="admin-metrics">
      <article className="active-visitors"><small>현재 접속자</small><strong>{Number(active?.visitors ?? 0).toLocaleString("ko-KR")}</strong><span>최근 5분 안에 활동한 방문자</span></article>
      <article><small>오늘 방문자</small><strong>{Number(today?.visitors ?? 0).toLocaleString("ko-KR")}</strong><span>{Number(today?.views ?? 0).toLocaleString("ko-KR")}회 조회</span></article>
      <article><small>최근 7일 방문자</small><strong>{Number(week.visitors).toLocaleString("ko-KR")}</strong><span>{Number(week.views).toLocaleString("ko-KR")}회 조회</span></article>
      <article><small>최근 30일 방문자</small><strong>{Number(month.visitors).toLocaleString("ko-KR")}</strong><span>{Number(month.views).toLocaleString("ko-KR")}회 조회</span></article>
    </section>
    <section className="admin-section-heading admin-system-heading" id="system-health"><span>AUTOMATION HEALTH</span><h2>자동 운영 상태</h2><p>최근 자료와 동기화 시각만 확인하면 됩니다. 오래된 항목이 생길 때 점검하세요.</p></section>
    <section className="admin-metrics admin-system-health" aria-label="자동 운영 상태">
      <article><small>최근 말씀</small><strong>말씀</strong><span>{freshnessLabel(mediaFreshness?.sermon_at)}</span></article>
      <article><small>최근 찬양</small><strong>찬양</strong><span>{freshnessLabel(mediaFreshness?.praise_at)}</span></article>
      <article><small>최근 쇼츠</small><strong>쇼츠</strong><span>{freshnessLabel(mediaFreshness?.short_at)}</span></article>
      <article className={sermonSyncHealthy?"active-visitors":"needs-attention"}><small>말씀 자동 수집</small><strong>{sermonSyncHealthy?"정상":"점검 필요"}</strong><span>{freshnessLabel(mediaFreshness?.sermon_sync_at)}</span></article>
      <article className={praiseSyncHealthy?"active-visitors":"needs-attention"}><small>찬양 자동 수집</small><strong>{praiseSyncHealthy?"정상":"점검 필요"}</strong><span>{freshnessLabel(mediaFreshness?.praise_sync_at)}</span></article>
      <p className={`admin-retention-health ${retentionHealthy?"is-healthy":"needs-attention"}`}><strong>개인정보 자동 파기 · {retentionHealthy?"정상":"점검 필요"}</strong><span>마지막 실행 {freshnessLabel(mediaFreshness?.retention_at)}</span></p>
    </section>
    <section className="admin-panel admin-status-events"><div className="admin-panel-title"><div><small>CHURCH STATUS LOG</small><h2>최근 교회 공개 상태 변경</h2><p>전체 교회 수가 달라진 이유를 교회별로 확인합니다.</p></div><span>{statusEvents.results.length}건</span></div><div className="review-list">{statusEvents.results.length?statusEvents.results.map((event)=><article key={event.id}><div><span>{event.previous_status?`${statusLabel(event.previous_status)} → ${statusLabel(event.new_status)}`:"새 등록"}</span><time>{koreanTime(event.created_at)}</time></div><strong><a href={`/church/${event.church_id}`}>{event.church_name}</a></strong><p>{statusReasonLabel(event.reason)}</p></article>):<p className="admin-empty">이 기능 적용 이후의 변경부터 기록됩니다.</p>}</div></section>
    <section className="admin-grid analytics-grid">
      <article className="admin-panel analytics-wide"><div className="admin-panel-title"><div><small>최근 14일</small><h2>날짜별 방문</h2></div><span>빠진 날짜 없이 조회수 표시 · 막대에 올리면 방문자 표시</span></div><TrafficChart rows={daily.results} label={(period)=>`${Number(period.slice(5,7))}/${Number(period.slice(8,10))}`} empty="방문 기록이 없습니다." /></article>
      <article className="admin-panel"><div className="admin-panel-title"><div><small>최근 24시간</small><h2>시간별 방문</h2></div><span>빠진 시간 없이 표시</span></div><TrafficChart rows={hourly.results} label={(period)=>`${Number(period.slice(11,13))}시`} empty="방문 기록이 없습니다." /></article>
      <article className="admin-panel"><div className="admin-panel-title"><div><small>최근 12개월</small><h2>월별 방문</h2></div><span>빠진 달 없이 표시</span></div><TrafficChart rows={monthly.results} label={(period)=>`${Number(period.slice(5))}월`} empty="방문 기록이 없습니다." /></article>
    </section>

    <ChurchDetailImporter/>
    <section className="admin-management-grid">
      <article className="admin-panel" id="church-management"><div className="admin-panel-title"><div><small>CHURCH MANAGEMENT</small><h2>전체 교회 관리</h2><p>처음에는 무작위 20곳만 표시하고, 검색할 때 전체 교회에서 필요한 결과만 불러옵니다.</p></div><span>{churches?.count??0}곳</span></div><AdminChurchDirectory variant="public" initialItems={safeChurchRows(publicChurchRows.results)} total={churches?.count??0}/></article>
      <article className="admin-panel" id="church-hold"><div className="admin-panel-title"><div><small>CHURCH HOLD</small><h2>보류 교회</h2><p>처음에는 무작위 10곳만 표시하고, 검색할 때 전체 보류 교회에서 필요한 결과만 불러옵니다.</p></div><span>{heldChurches?.count??0}곳</span></div><AdminChurchDirectory variant="held" initialItems={safeChurchRows(heldChurchRows.results)} total={heldChurches?.count??0}/></article>
    </section>

    <section className="admin-review-grid">
      <article className="admin-panel" id="ministry-suggestions"><div className="admin-panel-title"><div><small>MINISTRY SUGGESTIONS</small><h2>빠진 교역자 제보</h2><p>교회·교단·노회의 공식 출처를 직접 확인한 뒤 반영합니다.</p></div><span>{ministrySuggestionRows.results.length}건</span></div><div className="review-list">{ministrySuggestionRows.results.length?ministrySuggestionRows.results.map((item)=>{const source=safeHttpUrl(item.source_url);return <article key={item.id}><div><span>{item.church_name} · {statusLabel(item.status)}</span><time>{koreanTime(item.created_at)}</time></div><strong>{item.name} · {item.role_title}</strong><p>{item.note}</p>{source?<a className="admin-review-link" href={source} target="_blank" rel="noreferrer">공식 출처 확인 ↗</a>:<span className="admin-reference-missing">출처 링크 없음 · 반영 전 추가 확인 필요</span>}<ReviewControls kind="ministry-suggestion" id={item.id} status={item.status}/></article>}):<p className="admin-empty">검토할 교역자 제보가 없습니다.</p>}</div></article>
      <article className="admin-panel" id="encouragement-messages"><div className="admin-panel-title"><div><small>ENCOURAGEMENT</small><h2>교회·목사 응원글 전체</h2><p>공개 글과 보류 글을 함께 확인하고 보류·복원·삭제합니다.</p></div><span>{encouragementRows.results.length}건</span></div><div className="review-list">{encouragementRows.results.length?encouragementRows.results.map((item)=><article key={item.id}><div><span>{item.target_type==="pastor"?`${item.pastor} 목사`:`${item.church_name} 교회`} · {statusLabel(item.status)}</span><time>{koreanTime(item.created_at)}</time></div><strong>{item.nickname}</strong><p>{item.content}</p><a className="admin-review-link" href={item.target_type==="pastor"?`/pastors/${item.church_id}`:`/church/${item.church_id}`}>해당 페이지 보기 ↗</a><ReviewControls kind="encouragement" id={item.id} status={item.status}/></article>):<p className="admin-empty">아직 등록된 응원글이 없습니다.</p>}</div></article>
      <article className="admin-panel" id="contact-requests"><div className="admin-panel-title"><div><small>CONTACT REQUESTS</small><h2>운영 문의</h2><p>권리자 비공개 요청과 정보 수정 요청을 먼저 확인합니다.</p></div><span>{contactRows.results.length}건</span></div><div className="review-list">{contactRows.results.length?contactRows.results.map((item)=><article key={item.id}><div><span>{item.category} · {contactStatusLabel(item.status)}</span><time>{koreanTime(item.created_at)}</time></div><strong>{item.name}</strong><p>{item.contact}</p><p>{item.message}</p><ReviewControls kind="contact" id={item.id} status={item.status}/></article>):<p className="admin-empty">접수된 운영 문의가 없습니다.</p>}</div></article>
      <article className="admin-panel" id="reviewer-accounts"><div className="admin-panel-title"><div><small>REVIEWER ACCOUNTS</small><h2>목회자 검토 참여 신청</h2><p>성함과 연락처를 확인한 뒤 교회 검토 참여를 승인해 주세요.</p></div><span>{reviewerRows.results.length}명</span></div><div className="review-list">{reviewerRows.results.length?reviewerRows.results.map((item)=><article key={item.id}><div><span>{statusLabel(item.status)}</span><time>{koreanTime(item.created_at)}</time></div><strong>{item.name} · {item.username}</strong><p>{item.contact}</p><ReviewerAccountControls id={item.id} status={item.status}/></article>):<p className="admin-empty">목회자 참여 신청이 없습니다.</p>}</div></article>
      <article className="admin-panel" id="church-recommendations"><div className="admin-panel-title"><div><small>CHURCH RECOMMENDATIONS</small><h2>교회 추천 검토</h2><p>교단 소속과 공식 채널을 직접 확인한 뒤 등록을 승인해 주세요.</p></div><span>{recommendationRows.results.length}건</span></div><div className="review-list">{recommendationRows.results.length?recommendationRows.results.map((item)=>{const youtube=safeHttpUrl(item.youtube_url);return <article key={item.id}><div><span>{item.region} · {statusLabel(item.status)}</span><time>{koreanTime(item.created_at)}</time></div><strong>{item.church_name} · {item.pastor}</strong><p>{item.denomination}</p><p>{item.reason}</p>{youtube?<a className="admin-review-link" href={youtube} target="_blank" rel="noreferrer">공식 YouTube 확인 ↗</a>:<span className="admin-reference-missing">등록된 확인 링크 없음</span>}<ReviewControls kind="recommendation" id={item.id} status={item.status}/></article>}):<p className="admin-empty">접수된 교회 추천이 없습니다.</p>}</div></article>
      <article className="admin-panel" id="pending-posts"><div className="admin-panel-title"><div><small>COMMUNITY REVIEW</small><h2>익명 글 관리</h2></div><span>{postRows.results.length}건</span></div><div className="review-list">{postRows.results.length ? postRows.results.map((post) => <article key={post.id}><div><span>{post.category} · {statusLabel(post.status)}{post.report_count?` · 신고 ${post.report_count}건`:""}</span><time>{koreanTime(post.created_at)}</time></div><strong>{post.nickname}</strong><p>{post.content}</p><ReviewControls kind="post" id={post.id} status={post.status} /></article>) : <p className="admin-empty">접수된 익명 글이 없습니다.</p>}</div></article>
      <article className="admin-panel" id="pending-talents"><div className="admin-panel-title"><div><small>TALENT REVIEW</small><h2>달란트 관리</h2></div><span>{talentRows.results.length}건</span></div><div className="review-list">{talentRows.results.length ? talentRows.results.map((talent) => <article key={talent.id}><div><span>{talent.region} · {statusLabel(talent.status)}</span><time>{koreanTime(talent.created_at)}</time></div><strong>{talent.title}</strong><p>{talent.description}</p><ReviewControls kind="talent" id={talent.id} status={talent.status} /></article>) : <p className="admin-empty">접수된 달란트가 없습니다.</p>}</div></article>
    </section>
    <p className="admin-privacy">현재 접속자는 1분마다 자동 갱신됩니다. IP 주소, 이름, 이메일은 방문 통계에 저장하지 않습니다. 동일 브라우저의 익명 식별값은 해시 처리하고 같은 페이지의 30분 이내 중복 조회는 제외합니다.</p>
  </main>;
}
