"use client";
import {useState} from "react";

type Person={directoryId:string;name:string;publicSummary:null;photoUrl:string|null;photoSourceUrl:string|null;photoSha256:string|null;photoReviewStatus:"pending";reviewStatus:"pending"};
type Role={personDirectoryId:string;existingChurchId:number|null;churchName:string;denomination:string;region:string;roleTitle:string;roleCategory:string;roleStatus:"current"|"former";startDate:string|null;endDate:string|null;sourceUrl:string;reviewStatus:"pending"};
type Link={leftPersonDirectoryId:string;rightPersonDirectoryId:string;evidenceType:string;evidenceValue:string;status:"pending"};
type Plan={metadata?:{automaticApproval?:boolean;databaseWrites?:number;privateDataIncluded?:boolean;people?:number;roles?:number;identityLinks?:number};people?:Person[];roles?:Role[];identityLinks?:Link[]};

async function digest(value:unknown){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(value)));return [...new Uint8Array(bytes)].map((item)=>item.toString(16).padStart(2,"0")).join("")}
async function send(payload:Record<string,unknown>){const response=await fetch("/api/admin/pastor-data/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,digest:await digest(payload)})});const result=await response.json() as {error?:string;people?:number;roles?:number;identityLinks?:number};if(!response.ok)throw new Error(result.error||"목회자 자료를 반영하지 못했습니다.");return result;}

export default function PastorDataImporter(){
  const [plan,setPlan]=useState<Plan|null>(null),[name,setName]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function choose(file:File|null){setPlan(null);setMessage("");setName(file?.name??"");if(!file)return;try{const value=JSON.parse(await file.text()) as Plan;if(!Array.isArray(value.people)||!Array.isArray(value.roles)||!Array.isArray(value.identityLinks)||value.metadata?.automaticApproval!==false||Number(value.metadata?.databaseWrites)!==0||value.metadata?.privateDataIncluded!==false)throw new Error("검증 대기 상태의 목회자 import plan이 아닙니다.");setPlan(value);}catch(reason){setMessage((reason as Error).message)}}
  async function apply(){if(!plan?.people||!plan.roles||!plan.identityLinks)return;if(!window.confirm(`${plan.people.length.toLocaleString("ko-KR")}명의 목회자와 ${plan.roles.length.toLocaleString("ko-KR")}건의 사역 관계를 모두 비공개 검토 대기로 가져올까요?`))return;setBusy(true);setMessage("");try{let people=0,roles=0,identityLinks=0;for(let offset=0;offset<plan.people.length;offset+=100){const selected=plan.people.slice(offset,offset+100),ids=new Set(selected.map((item)=>item.directoryId)),payload={kind:"people",people:selected,roles:plan.roles.filter((item)=>ids.has(item.personDirectoryId)),links:[]};const result=await send(payload);people+=result.people??0;roles+=result.roles??0;setMessage(`목회자 ${Math.min(offset+100,plan.people.length).toLocaleString("ko-KR")} / ${plan.people.length.toLocaleString("ko-KR")}명 처리 중…`);}for(let offset=0;offset<plan.identityLinks.length;offset+=100){const payload={kind:"identities",people:[],roles:[],links:plan.identityLinks.slice(offset,offset+100)};const result=await send(payload);identityLinks+=result.identityLinks??0;}setMessage(`검토 대기 목회자 ${people.toLocaleString("ko-KR")}명, 사역 관계 ${roles.toLocaleString("ko-KR")}건, 동일인 검토 후보 ${identityLinks.toLocaleString("ko-KR")}건을 준비했습니다.`);setPlan(null);setName("");}catch(reason){setMessage(`${(reason as Error).message} 이미 처리된 묶음은 안전하게 유지되며 같은 파일로 다시 이어갈 수 있습니다.`)}finally{setBusy(false)}}
  return <section className="admin-panel admin-detail-import"><div className="admin-panel-title"><div><small>PASTOR DATA IMPORT</small><h2>목회자 검토 자료 가져오기</h2><p>목회자·사역 관계·동일인 후보를 100명씩 비공개 검토 대기로 저장합니다. 승인이나 사진 공개는 자동으로 하지 않습니다.</p></div><span>100명씩 처리</span></div><label><span>목회자 import plan JSON</span><input type="file" accept="application/json,.json" disabled={busy} onChange={(event)=>void choose(event.target.files?.[0]??null)}/></label>{plan&&<div className="admin-import-summary"><strong>{plan.people?.length.toLocaleString("ko-KR")}명 · 사역 {plan.roles?.length.toLocaleString("ko-KR")}건 · {name}</strong><span>자동 승인 없음 · 개인정보 없음</span></div>}<button type="button" disabled={busy||!plan} onClick={()=>void apply()}>{busy?"검토 대기 자료 준비 중…":"목회자 검토 자료 가져오기"}</button>{message&&<p role="status">{message}</p>}</section>;
}
