import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

const read=(path)=>readFile(new URL(path,import.meta.url),"utf8");
test("ministry suggestions remain pending and reject personal social sources",async()=>{const [route,admin]=await Promise.all([read("../app/api/ministry-suggestions/route.ts"),read("../app/api/admin/manage/route.ts")]);assert.match(route,/status,fingerprint\) SELECT \?,\?,\?,\?,\?,'pending'/);assert.match(route,/personal_social|개인 SNS/);assert.match(route,/consumeSubmissionLimit\(db,"ministry-suggestion",fp,3,1440\)/);assert.match(admin,/kind==="ministry-suggestion"/);assert.match(admin,/review_status\) VALUES \(\?,\?,\?,\?,\?,\?,CURRENT_TIMESTAMP,'approved'\)/)});
test("church and pastor pages expose only approved ministry profiles",async()=>{const [church,pastor]=await Promise.all([read("../app/church/[id]/page.tsx"),read("../app/pastors/[id]/page.tsx")]);assert.match(church,/FROM church_ministry_profiles WHERE church_id=\? AND review_status='approved'/);assert.match(pastor,/FROM church_ministry_profiles WHERE id=\? AND church_id=\? AND review_status='approved'/);assert.match(pastor,/targetRef=\{targetRef\}/);assert.doesNotMatch(pastor,/아직 연결된 공개 말씀 기록이 없습니다/)});
test("minister metadata and admin encouragement links preserve the selected minister",async()=>{const [pastor,admin]=await Promise.all([read("../app/pastors/[id]/page.tsx"),read("../app/admin/page.tsx")]);assert.match(pastor,/generateMetadata\(\{params,searchParams\}/);assert.match(pastor,/canonical=`\/pastors\/\$\{church\.id\}\$\{minister\?/);assert.match(admin,/e\.target_ref=\('minister:' \|\| m\.id\)/);assert.match(admin,/\?minister=\$\{item\.minister_id\}/)});
test("pastor pages separate reviewed appearances from title-attributed church sermons",async()=>{const [pastor,schema,shared,attribution]=await Promise.all([read("../app/pastors/[id]/page.tsx"),read("../db/schema.ts"),read("../app/api/_shared.ts"),read("../app/pastor-sermon-attribution.ts")]);assert.match(pastor,/FROM ministry_appearances WHERE church_id=\? AND minister_name=\? AND review_status='approved'/);assert.match(pastor,/isSermonAttributedTo\(sermon\.title,displayName,!minister\)/);assert.match(schema,/ministryAppearances=sqliteTable\("ministry_appearances"/);assert.match(shared,/schema-ministry-profiles-v2/);assert.match(attribution,/isPrimary&&named\.length===0/);assert.match(attribution,/named\.includes\(subject\)/)});
