"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import HomeReloadLink from "../home-reload-link";
import { normalizeSearchValue } from "../search-domain";
import { isSavedItem, readSavedItems, SavedItem, writeSavedItems } from "../saved-items";
import { recordDailyMediaStep } from "../daily-media-link";

const groups=[{kind:"sermon" as const,label:"말씀",empty:"아직 찜한 말씀이 없습니다."},{kind:"praise" as const,label:"찬양",empty:"아직 찜한 찬양이 없습니다."},{kind:"church" as const,label:"교회",empty:"아직 찜한 교회가 없습니다."},{kind:"pastor" as const,label:"목사",empty:"아직 찜한 목사님이 없습니다."}];

export default function SavedClient(){
  const [items,setItems]=useState<SavedItem[]>([]),[ready,setReady]=useState(false),[filter,setFilter]=useState(""),[notice,setNotice]=useState(""),[sort,setSort]=useState<"recent"|"title">("recent");
  const importRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{setItems(readSavedItems());setReady(true);},[]);
  const remove=(item:SavedItem)=>{setItems((current)=>writeSavedItems(current.filter((candidate)=>candidate.id!==item.id)));setNotice(`${item.title}을(를) 나의 모음에서 삭제했습니다.`);};
  const exportItems=()=>{const blob=new Blob([JSON.stringify({service:"airChurch",version:1,exportedAt:new Date().toISOString(),items},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`airchurch-saved-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setNotice(`${items.length}개 항목을 백업했습니다.`);};
  const importItems=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;try{if(file.size>200_000)throw new Error();const parsed=JSON.parse(await file.text()),candidates=Array.isArray(parsed)?parsed:parsed?.items;if(!Array.isArray(candidates))throw new Error();const valid=candidates.filter(isSavedItem),merged=writeSavedItems([...valid,...items]);if(!valid.length&&candidates.length)throw new Error();setItems(merged);setNotice(`${valid.length}개를 확인해 현재 모음과 합쳤습니다${merged.length===30?" (최대 30개)":""}.`);}catch{setNotice("airChurch에서 만든 올바른 백업 파일인지 확인해 주세요.");}};
  const normalized=normalizeSearchValue(filter),matchedItems=normalized?items.filter((item)=>normalizeSearchValue(`${item.title}${item.subtitle}`).includes(normalized)):items,visibleItems=sort==="title"?[...matchedItems].sort((a,b)=>a.title.localeCompare(b.title,"ko")):matchedItems;
  return <main className="saved-shell"><header className="saved-header"><HomeReloadLink className="brand"><span className="brand-mark" aria-hidden="true"/><span>airchurch</span></HomeReloadLink><nav><a href="/search">통합 검색</a><a href="/#church-directory">교회 찾기</a><a href="/">홈으로</a></nav></header><section className="saved-hero"><span>LOCAL COLLECTION</span><h1>나의 모음</h1><p>로그인 없이 이 브라우저에만 보관한 말씀과 찬양, 교회와 목회자입니다.<br/>다른 기기나 브라우저에는 전송되지 않습니다.</p><label className="saved-filter"><span aria-hidden="true">⌕</span><input type="search" inputMode="search" enterKeyHint="search" autoCapitalize="none" spellCheck={false} value={filter} onChange={(event)=>setFilter(event.target.value)} placeholder="저장한 말씀·찬양·교회·목회자 찾기" aria-label="나의 모음 검색"/>{filter&&<button className="saved-filter-clear" type="button" onClick={()=>setFilter("")} aria-label="검색어 지우기">검색 초기화</button>}</label><div className="saved-tools"><button type="button" onClick={exportItems} disabled={!items.length}>백업 파일 받기</button><button type="button" onClick={()=>importRef.current?.click()}>백업 불러오기</button><input ref={importRef} type="file" accept="application/json,.json" onChange={importItems} aria-label="나의 모음 백업 파일 선택"/><label>정렬<select value={sort} onChange={(event)=>setSort(event.target.value as "recent"|"title")}><option value="recent">최근 저장순</option><option value="title">이름순</option></select></label><span aria-live="polite">{notice}</span></div><b>{ready?(filter?`${visibleItems.length}개 찾음`:`${items.length}개 저장됨`):"불러오는 중"}</b></section><div className="saved-content">{groups.map((group)=>{const grouped=visibleItems.filter((item)=>item.kind===group.kind);return <section className="saved-group" key={group.kind}><div className="saved-group-heading"><h2>{group.label}</h2><span>{grouped.length}개</span></div>{ready&&grouped.length>0?<div className="saved-grid">{grouped.map((item)=><article key={item.id}><span>{group.label}</span><a href={item.url} target={item.url.startsWith("http")?"_blank":undefined} rel={item.url.startsWith("http")?"noopener noreferrer":undefined} onClick={()=>{if(item.kind==="sermon"||item.kind==="praise")recordDailyMediaStep(item.kind);}}><strong>{item.title}</strong><small>{item.subtitle}</small><em>이어보기 →</em></a><button type="button" onClick={()=>remove(item)} aria-label={`${item.title} 나의 모음에서 삭제`}>×</button></article>)}</div>:ready?<p className="saved-empty">{filter?"검색 조건에 맞는 항목이 없습니다.":group.empty} {filter&&<button type="button" className="saved-clear-results" onClick={()=>setFilter("")}>검색어 지우고 전체 보기</button>}{!filter&&<a href={group.kind==="church"?"/#church-directory":group.kind==="pastor"?"/#pastor-directory":group.kind==="sermon"?"/#sermons":"/#praises"}>둘러보기 →</a>}</p>:null}</section>})}</div><footer className="church-detail-footer"><a href="/">airChurch 홈</a><span>백업과 복원도 서버 전송 없이 이 브라우저 안에서 처리됩니다.</span></footer></main>;
}
