"use client";
import { FormEvent,useState } from "react";

export type EncouragementItem={id:number;nickname:string;content:string;createdAt:string};
export default function EncouragementBoard({churchId,targetType,title,initialItems}:{churchId:number;targetType:"church"|"pastor";title:string;initialItems:EncouragementItem[]}){
  const [items,setItems]=useState(initialItems),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=event.currentTarget,data=new FormData(form);try{const last=Number(localStorage.getItem("airchurch.encouragement.lastAt")||0);if(Date.now()-last<30*60*1000)throw new Error("응원글은 같은 브라우저에서 30분에 한 번 남길 수 있습니다.");let browserToken=localStorage.getItem("airchurch.encouragement.browserId");if(!browserToken){browserToken=crypto.randomUUID();localStorage.setItem("airchurch.encouragement.browserId",browserToken);}const response=await fetch("/api/encouragements",{method:"POST",headers:{"content-type":"application/json","x-airchurch-browser":browserToken},body:JSON.stringify({churchId,targetType,nickname:data.get("nickname"),content:data.get("content"),company:data.get("company")})});const result=await response.json() as {error?:string;item?:EncouragementItem};if(!response.ok)throw new Error(result.error||"응원글을 남기지 못했습니다.");if(result.item)setItems((current)=>[result.item!,...current].slice(0,30));localStorage.setItem("airchurch.encouragement.lastAt",String(Date.now()));form.reset();setMessage("응원하는 마음을 전했습니다.");}catch(reason){setMessage((reason as Error).message);}finally{setBusy(false)}}
  return <section className="encouragement-board"><div className="section-heading"><div><span className="section-kicker">ENCOURAGEMENT</span><h2>{title}</h2><p>따뜻한 응원과 감사만 남겨 주세요. 같은 브라우저에서는 30분에 한 번 작성할 수 있습니다.</p></div><span className="result-count">최근 {items.length}개</span></div><form onSubmit={submit}><label><span>이름</span><input name="nickname" minLength={2} maxLength={16} placeholder="이름 또는 별칭" required/></label><label className="encouragement-content"><span>응원의 글</span><textarea name="content" minLength={5} maxLength={300} rows={3} placeholder="교회와 목사님께 힘이 되는 말을 남겨 주세요." required/></label><input className="honeypot" name="company" tabIndex={-1} autoComplete="off" aria-hidden="true"/><button type="submit" disabled={busy}>{busy?"전하는 중…":"응원 남기기"}</button><p className="encouragement-notice">연락처·민원·비방·광고는 남기지 말아 주세요. 공개 기준에 맞지 않으면 보류 또는 삭제될 수 있습니다.</p>{message&&<p className="encouragement-message" role="status">{message}</p>}</form><div className="encouragement-list">{items.length?items.map((item)=><article key={item.id}><div><strong>{item.nickname}</strong><time>{new Date(item.createdAt.endsWith("Z")?item.createdAt:`${item.createdAt}Z`).toLocaleDateString("ko-KR",{timeZone:"Asia/Seoul"})}</time></div><p>{item.content}</p></article>):<p className="empty">첫 응원을 기다리고 있습니다.</p>}</div></section>;
}
