"use client";
import { useEffect, useState, type FormEvent } from "react";
type Comment = {id:number;nickname:string;content:string;createdAt:string};
export default function MakingComments({slug}:{slug:string}) {
  const [items,setItems]=useState<Comment[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function load() {setLoading(true);setLoadError("");try {const response=await fetch(`/api/making/comments?slug=${encodeURIComponent(slug)}`);const data=await response.json();if(!response.ok)throw new Error(data.error);setItems(data.items);}catch{setLoadError("댓글을 불러오지 못했습니다.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[slug]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setMessage("");try {const response=await fetch("/api/making/comments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(new FormData(form)),slug})});const data=await response.json();if(!response.ok)throw new Error(data.error);form.reset();setMessage("댓글을 접수했습니다. 관리자 확인 후 공개됩니다.");}catch(error){setMessage(error instanceof Error?error.message:"저장하지 못했습니다. 다시 시도해 주세요.");}finally{setBusy(false);}}
  return <section className="making-comments" aria-labelledby="making-comments-title"><h2 id="making-comments-title">함께 나누는 의견</h2><p>이 고민에 대한 생각을 남겨 주세요. 댓글은 관리자 확인 후 공개됩니다.</p>{loading?<p role="status">댓글을 불러오는 중입니다.</p>:loadError?<p role="alert">{loadError} <button type="button" onClick={()=>void load()}>다시 불러오기</button></p>:items.length?<ul className="making-comment-list">{items.map(item=><li key={item.id}><b>{item.nickname}</b> <time dateTime={item.createdAt}>{item.createdAt.slice(0,10)}</time><p>{item.content}</p></li>)}</ul>:<p>첫 의견을 남겨 주세요.</p>}<form className="making-form" onSubmit={submit}><label>별명<input name="nickname" minLength={2} maxLength={16} required autoComplete="nickname" /></label><label>댓글<textarea name="content" minLength={5} maxLength={1000} required rows={4} /></label><div hidden aria-hidden="true"><label>회사<input name="company" tabIndex={-1} autoComplete="off" /></label></div><small>별명과 댓글이 공개됩니다. 연락처 등 개인정보는 적지 말아 주세요.</small><button type="submit" disabled={busy}>{busy?"접수 중…":"댓글 남기기"}</button><p role="status">{message}</p></form></section>;
}
