"use client";

import { FormEvent, useMemo, useRef, useState } from "react";

type Church={id:number;name:string;pastor:string;region:string;denomination:string;review_status:string;homepage_url:string|null;youtube_channel_id:string|null;channel_image_url:string|null};
type RequestItem={id:number;church_name:string;request_type:string;reason:string;status:string;admin_note:string|null;created_at:string;proposed_name:string|null;proposed_pastor:string|null;proposed_region:string|null;proposed_denomination:string|null};

const historyActionLabels={edit:"정보 수정 제안",hold:"보류 제안",delete:"이전 삭제 요청"} as const;
const statusLabels={pending:"관리자 확인 대기",approved:"승인",rejected:"반려",deferred:"일단 보류"} as const;
function denominationMark(denomination:string){const marks:Record<string,string>={"대한예수교장로회 통합":"pck-tonghap.png","대한예수교장로회 합동":"pck-hapdong.svg","기독교대한감리회":"kmc.ico","대한예수교장로회 고신":"pck-kosin.jpg","기독교한국침례회":"kbch.png","기독교대한성결교회":"kehc-256.png","대한예수교장로회 합신":"pck-hapshin.png","대한예수교장로회 백석":"pck-baekseok-256.png","기독교대한하나님의성회":"agk.png","기독교대한하나님의성회 광화문총회":"agk-gwanghwamun.png","한국기독교장로회":"prok-256.png","한국독립교회선교단체연합회":"kaicam.png"};return marks[denomination]?`/denominations/${marks[denomination]}`:null;}
async function sendProposal(body:Record<string,unknown>){
  const response=await fetch("/api/admin/manage",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"church-change-request",...body})});
  const result=await response.json().catch(()=>({})) as {error?:string};
  if(!response.ok)throw new Error(result.error||"제안을 보내지 못했습니다.");
}

export default function ChurchRequestManager({total,featuredChurches,requests}:{total:number;featuredChurches:Church[];requests:RequestItem[]}) {
  const [query,setQuery]=useState(""),[appliedQuery,setAppliedQuery]=useState(""),[results,setResults]=useState(featuredChurches),[resultTotal,setResultTotal]=useState(total),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[holdChurches,setHoldChurches]=useState<Church[]>([]),[editingId,setEditingId]=useState<number|null>(null),[busy,setBusy]=useState(false),[searching,setSearching]=useState(false),[message,setMessage]=useState("");
  const searchRef=useRef<AbortController|null>(null),holdIds=useMemo(()=>new Set(holdChurches.map((church)=>church.id)),[holdChurches]);
  const pages=Math.max(1,Math.ceil(resultTotal/pageSize));

  async function loadChurches(nextQuery="",nextPage=1){
    searchRef.current?.abort();const controller=new AbortController();searchRef.current=controller;setSearching(true);setMessage("");const params=new URLSearchParams({page:String(nextPage)});if(nextQuery.trim())params.set("q",nextQuery.trim());
    try{const response=await fetch(`/api/pastor/churches?${params}`,{cache:"no-store",signal:controller.signal});const data=await response.json() as {items?:Church[];total?:number;page?:number;pageSize?:number;error?:string};if(!response.ok)throw new Error(data.error||"교회를 찾지 못했습니다.");setResults(data.items??[]);setResultTotal(data.total??0);setPageSize(data.pageSize??24);setPage(data.page??nextPage);setAppliedQuery(nextQuery.trim());setEditingId(null);}catch(reason){if((reason as {name?:string}).name!=="AbortError")setMessage((reason as Error).message);}finally{if(!controller.signal.aborted)setSearching(false);}
  }

  function toggleHold(church:Church){if(!holdIds.has(church.id)&&holdChurches.length>=20){setMessage("한 번에 20곳까지 보류를 제안할 수 있습니다.");return;}setMessage("");setHoldChurches((current)=>current.some((item)=>item.id===church.id)?current.filter((item)=>item.id!==church.id):[...current,church]);if(editingId===church.id)setEditingId(null);}
  function openEdit(id:number){setEditingId((current)=>current===id?null:id);setHoldChurches((current)=>current.filter((church)=>church.id!==id));setMessage("");}

  async function submitEdit(event:FormEvent<HTMLFormElement>,church:Church){
    event.preventDefault();if(busy)return;setBusy(true);setMessage("");const values=Object.fromEntries(new FormData(event.currentTarget));
    try{await sendProposal({id:church.id,requestType:"edit",reason:values.reason,name:values.name,pastor:values.pastor,region:values.region,denomination:values.denomination});setMessage(`${church.name} 정보 수정 제안을 보냈습니다.`);setEditingId(null);window.setTimeout(()=>window.location.reload(),500);}catch(reason){setMessage((reason as Error).message);setBusy(false);}
  }

  async function submitHold(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(!holdChurches.length||busy)return;setBusy(true);setMessage("");const values=Object.fromEntries(new FormData(event.currentTarget));
    const accepted=new Set<number>();
    try{for(let offset=0;offset<holdChurches.length;offset+=3){const chunk=holdChurches.slice(offset,offset+3),settled=await Promise.allSettled(chunk.map((church)=>sendProposal({id:church.id,requestType:"hold",reason:values.reason})));settled.forEach((result,index)=>{if(result.status==="fulfilled")accepted.add(chunk[index].id);});const failed=settled.find((result):result is PromiseRejectedResult=>result.status==="rejected");if(failed)throw failed.reason;}setMessage(`${holdChurches.length}곳에 보류 제안을 보냈습니다.`);setHoldChurches([]);window.setTimeout(()=>window.location.reload(),500);}catch(reason){setHoldChurches((current)=>current.filter((church)=>!accepted.has(church.id)));setMessage(accepted.size?`${accepted.size}곳은 접수했습니다. 나머지는 다시 확인해 주세요. · ${(reason as Error).message}`:(reason as Error).message);setBusy(false);}
  }

  return <>
    <section className="admin-panel pastor-request-panel"><div className="admin-panel-title"><div><small>교회 정보 제안</small><h2>교회를 찾아 제안하세요</h2><p>정보 수정은 한 교회씩, 보류는 여러 교회를 한 번에 제안할 수 있습니다.</p></div><span>{total}곳</span></div>
      <form className="pastor-church-search" role="search" onSubmit={(event)=>{event.preventDefault();void loadChurches(query);}}><label><span>교회 검색</span><input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="교회, 목사, 지역, 교단 검색"/></label><button type="submit" disabled={searching}>{searching?"검색 중…":"검색"}</button></form>
      <p className="pastor-search-guide" aria-live="polite">{appliedQuery?`전체 일치 ${resultTotal}곳 · 현재 ${results.length}곳 표시`:`무작위로 고른 교회 ${results.length}곳`} · 카드에서 원하는 제안 버튼을 누르세요.</p>
      {holdChurches.length>0&&<button className="pastor-selection-bar" type="button" onClick={()=>document.querySelector(".pastor-hold-form")?.scrollIntoView({behavior:"smooth",block:"center"})}><span>보류로 고른 교회 <b>{holdChurches.length}곳</b></span><strong>보류 이유 작성하기 ↓</strong></button>}
      <div className="pastor-search-results">{results.length?results.map((church)=>{const selectedForHold=holdIds.has(church.id),isEditing=editingId===church.id,mark=denominationMark(church.denomination);return <article className={`managed-church-card${selectedForHold?" is-selected":""}`} key={church.id}><div className="pastor-church-main"><span className="managed-church-card-top"><span>{church.region}</span><span><b className={`status-${church.review_status}`}>공개</b>{mark&&<img src={mark} alt={`${church.denomination} 교단 심볼`} loading="lazy" decoding="async"/>}</span></span><span className="managed-church-card-copy"><strong>{church.name}</strong><span>{church.pastor}</span><small>{church.denomination}</small></span></div><div className="pastor-church-links">{church.homepage_url&&<a href={church.homepage_url} target="_blank" rel="noreferrer" aria-label={`${church.name} 홈페이지 열기`}><span className="homepage-visual" aria-hidden="true"><span>⛪</span>{church.channel_image_url&&<img src={church.channel_image_url} alt="" loading="lazy" decoding="async" referrerPolicy="no-referrer"/>}</span><b>홈페이지 ↗</b></a>}{church.youtube_channel_id&&<a className="pastor-youtube-link" href={`https://www.youtube.com/channel/${church.youtube_channel_id}`} target="_blank" rel="noreferrer" aria-label={`${church.name} YouTube 열기`}><span className="directory-icon youtube-icon" aria-hidden="true"/><b>YouTube ↗</b></a>}{!church.homepage_url&&!church.youtube_channel_id&&<span className="pastor-reference-empty"><i aria-hidden="true">—</i><b>등록된 확인 링크 없음</b></span>}</div><div className="pastor-proposal-buttons"><button className="pastor-edit-proposal" aria-expanded={isEditing} type="button" onClick={()=>openEdit(church.id)}>{isEditing?"수정 닫기":"내용 수정하기"}</button><button className="pastor-hold-proposal" aria-pressed={selectedForHold} type="button" onClick={()=>toggleHold(church)}>{selectedForHold?"✓ 보류로 보낼 교회":"보류로 보내기"}</button></div>{isEditing&&<form className="pastor-inline-edit" onSubmit={(event)=>void submitEdit(event,church)}><strong>{church.name} 수정할 내용</strong><div className="pastor-edit-fields"><label>교회명<input name="name" defaultValue={church.name} required maxLength={100}/></label><label>담임목사<input name="pastor" defaultValue={church.pastor} required maxLength={80}/></label><label>지역<input name="region" defaultValue={church.region} required maxLength={80}/></label><label>교단<input name="denomination" defaultValue={church.denomination} required maxLength={120}/></label></div><label className="admin-note-field"><span>수정 이유</span><textarea name="reason" required minLength={3} maxLength={500} rows={3} placeholder="어떤 정보가 왜 달라져야 하는지 적어 주세요."/></label><div className="admin-action-row"><button disabled={busy} type="submit">수정 내용 제안하기</button><button disabled={busy} type="button" onClick={()=>setEditingId(null)}>취소</button></div></form>}</article>}):<p className="admin-empty">검색 결과가 없습니다.</p>}</div>
      {appliedQuery&&pages>1&&<nav className="admin-directory-pagination" aria-label="목회자 교회 검색 페이지"><button type="button" disabled={searching||page<=1} onClick={()=>void loadChurches(appliedQuery,page-1)}>이전</button><span>{page}/{pages}</span><button type="button" disabled={searching||page>=pages} onClick={()=>void loadChurches(appliedQuery,page+1)}>다음</button></nav>}
      {!query.trim()&&!appliedQuery&&total>20&&<button className="pastor-random-refresh" type="button" disabled={searching} onClick={()=>void loadChurches()}>↻ 다른 교회 20곳 보기</button>}
      {holdChurches.length>0&&<form className="pastor-request-form pastor-hold-form" onSubmit={submitHold}><div className="pastor-request-selected"><strong>보류를 제안할 교회 {holdChurches.length}곳</strong><span>{holdChurches.map((church)=>church.name).join(" · ")}</span></div><label className="admin-note-field"><span>보류 이유</span><textarea name="reason" required minLength={3} maxLength={500} rows={4} placeholder="이 교회들을 보류해야 하는 이유를 적어 주세요."/></label><div className="admin-action-row"><button type="submit" disabled={busy}>{busy?"보내는 중…":`${holdChurches.length}곳 한 번에 보류 제안`}</button><button type="button" disabled={busy} onClick={()=>setHoldChurches([])}>선택 취소</button></div></form>}
      {message&&<p className="admin-success" role="status">{message}</p>}
    </section>
    <section className="admin-panel pastor-request-history"><div className="admin-panel-title"><div><small>내 제안</small><h2>처리 결과</h2><p>관리자가 승인·반려·보류한 내용을 여기서 다시 볼 수 있습니다.</p></div><span>{requests.length}건</span></div><div className="review-list">{requests.length?requests.map((request)=><article key={request.id}><div><span>{historyActionLabels[request.request_type as keyof typeof historyActionLabels]??request.request_type} · {statusLabels[request.status as keyof typeof statusLabels]??request.status}</span><time>{new Date(`${request.created_at}Z`).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})}</time></div><strong>{request.church_name}</strong><p>{request.reason}</p>{request.request_type==="edit"&&<p>{request.proposed_name} · {request.proposed_pastor} · {request.proposed_region} · {request.proposed_denomination}</p>}{request.admin_note&&<p className="admin-reviewer-note">관리자 답변 · {request.admin_note}</p>}</article>):<p className="admin-empty">아직 보낸 제안이 없습니다.</p>}</div></section>
  </>;
}
