"use client";
import { useCallback,useEffect,useRef,useState,type FormEvent } from "react";
import { CONTEST,contestPhase,type ContestEntry } from "./config";
import previewVideos from "./preview-videos.json";
type Feed={items:ContestEntry[];phase:ReturnType<typeof contestPhase>|"cancelled";serverNow:string;votedEntryId:number|null;finalized:boolean};
const phaseLabels={upcoming:"10월 1일 시작",open:"영상 접수 · 좋아요 진행 중",voting:"접수 마감 · 좋아요 진행 중",finished:"최종 집계",cancelled:"참가작 부족으로 대회 취소"};
const previewEntries:ContestEntry[]=previewVideos.map((video,i)=>({...video,id:i+1,performer:video.channelName,createdAt:`2026-10-01T00:00:0${i}.000Z`,likes:[128,96,75,54,32,16,0,0][i],rank:i<6?i+1:null,prize:0}));
export default function ContestBoard({preview=false}:{preview?:boolean}){
 const [feed,setFeed]=useState<Feed|null>(preview?{items:previewEntries,phase:"open",serverNow:"2026-10-05T03:00:00Z",votedEntryId:null,finalized:false}:null),[error,setError]=useState(""),[message,setMessage]=useState(""),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[liking,setLiking]=useState<number|null>(null),[playing,setPlaying]=useState<number|null>(null),[highlight,setHighlight]=useState<number|null>(null),[updated,setUpdated]=useState("");
 const [shareEntry,setShareEntry]=useState<number|null>(null);
 const shareDialog=useRef<HTMLDialogElement>(null);
 const sharedItem=feed?.items.find(item=>item.id===shareEntry);
 const sharing=shareEntry!==null;
 useEffect(()=>{if(sharing&&!shareDialog.current?.open)shareDialog.current?.showModal();if(!sharing&&shareDialog.current?.open)shareDialog.current?.close();},[sharing]);
 const loading=useRef(false),lastServerOffset=useRef(0),active=useRef(true);
 const load=useCallback(async()=>{
  if(preview)return;
  if(loading.current)return;loading.current=true;
  try{const response=await fetch("/api/praise-contest",{cache:"no-store",signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok)throw new Error(data.error||"집계를 불러오지 못했습니다.");if(!active.current)return;setFeed(data);lastServerOffset.current=Date.parse(data.serverNow)-Date.now();setUpdated(new Date(data.serverNow).toLocaleTimeString("ko-KR",{timeZone:"Asia/Seoul"}));setError("");}
  catch(e){if(active.current)setError(e instanceof Error?e.message:"연결을 확인해 주세요.");}finally{loading.current=false;}
 },[preview]);
 useEffect(()=>{active.current=true;void load();let timer:number;
  const tick=()=>{if(document.visibilityState==="visible")void load();timer=window.setTimeout(tick,contestPhase(Date.now()+lastServerOffset.current)==="upcoming"?60000:10000);};timer=window.setTimeout(tick,10000);
  const onVisible=()=>{if(document.visibilityState==="visible")void load();};document.addEventListener("visibilitychange",onVisible);
  const linked=Number(new URL(window.location.href).searchParams.get("entry"));if(Number.isSafeInteger(linked)&&linked>0)setHighlight(linked);
  return()=>{active.current=false;window.clearTimeout(timer);document.removeEventListener("visibilitychange",onVisible);};
 },[load]);
 const highlightedPresent=Boolean(feed?.items.some(item=>item.id===highlight));
 useEffect(()=>{if(highlight&&highlightedPresent)document.getElementById(`entry-${highlight}`)?.scrollIntoView({block:"center",behavior:"smooth"});},[highlight,highlightedPresent]);
 const phase=feed?.phase??"upcoming",canVote=Boolean(feed&&(phase==="open"||phase==="voting")),canSubmit=Boolean(!preview&&feed&&phase==="open");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||preview)return;const form=event.currentTarget;const data=new FormData(form);setBusy(true);setMessage("");
  try{const body={...Object.fromEntries(data),rightsConsent:data.has("rightsConsent"),privacyConsent:data.has("privacyConsent"),payoutConsent:data.has("payoutConsent"),ageConsent:data.has("ageConsent")};const r=await fetch("/api/praise-contest",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const result=await r.json();if(!r.ok)throw new Error(result.error);form.reset();setShowForm(false);setHighlight(result.id);setMessage("등록되었습니다. 내 영상의 ‘공유하기’로 참가 소식을 알려보세요.");await load();}
  catch(e){setMessage(e instanceof Error?e.message:"접수를 완료하지 못했습니다.");}finally{setBusy(false);}
 }
 async function like(id:number){
  if(liking!==null)return;
  const undo=feed?.votedEntryId===id;
  if(preview){setFeed(current=>{if(!current||(current.votedEntryId!==null&&current.votedEntryId!==id))return current;const cancel=current.votedEntryId===id;const items=current.items.map(item=>item.id===id?{...item,likes:item.likes+(cancel?-1:1)}:item).sort((a,b)=>b.likes-a.likes||a.id-b.id).map((item,i)=>({...item,rank:item.likes?i+1:null}));return {...current,items,votedEntryId:cancel?null:id};});setMessage(undo?"예시 좋아요를 취소했습니다. 다른 작품을 선택할 수 있습니다.":"예시 좋아요입니다. 하트를 다시 누르면 취소됩니다.");return;}
  setLiking(id);setMessage("");try{const r=await fetch("/api/praise-contest/like",{method:undo?"DELETE":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entryId:id}),signal:AbortSignal.timeout(10000)});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage(undo?"좋아요를 취소했습니다. 다른 작품을 선택할 수 있습니다.":"좋아요가 반영되었습니다. 오늘 누른 하트를 다시 누르면 취소할 수 있습니다.");}catch(e){setMessage(e instanceof Error?e.message:"좋아요를 저장하지 못했습니다.");}finally{await load();setLiking(null);}
 }
 function shareUrl(id:number){if(id===0)return `${window.location.origin}/praise-contest`;return `${window.location.origin}/praise-contest${preview?"/preview":""}?entry=${id}`;}
 async function copyShare(id:number){try{await navigator.clipboard.writeText(shareUrl(id));setMessage("공유 링크를 복사했습니다. 카카오톡이나 문자에 붙여넣어 보내세요.");}catch{setMessage("아래 공유 주소를 길게 누르거나 선택해 복사해 주세요.");}}
 function shareText(item?:ContestEntry){return item?(preview?"찬양대회 예시 화면입니다. 실제 참가작이 아닙니다.":`${item.performer}님의 찬양 ‘${item.title}’을 함께 들어주세요. 마음에 닿았다면 오늘의 응원을 보내주세요.`):"당신의 찬양이 더 많은 사람에게 전해집니다. 에이처치 10월 찬양대회 · 10월 1~15일 영상 링크 접수 · 총상금 100만 원. 참가·시상 조건은 대회 페이지에서 확인하세요.";}
 async function copyInvitation(){try{await navigator.clipboard.writeText(`${shareText(sharedItem)}\n${shareUrl(sharedItem?.id??0)}`);setMessage("초대 글과 주소를 함께 복사했습니다.");}catch{setMessage("공유 창의 초대 글과 주소를 선택해 복사해 주세요.");}}
 async function nativeShare(item?:ContestEntry){try{await navigator.share({title:item?`${preview?"[미리보기] ":""}${item.performer} · ${item.title}`:"에이처치 10월 찬양대회",text:shareText(item),url:shareUrl(item?.id??0)});}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setMessage("초대 글 복사를 이용해 주세요.");}}

 return <>
 {preview&&<p className="contest-preview-note"><strong>미리보기</strong> 실제 찬양 영상 8개로 체험하는 예시 화면 · 응원 수는 연습용입니다. <a href="/praise-contest">실제 대회 페이지로 돌아가기</a></p>}
 <section className="contest-header" id="primary-content" tabIndex={-1}><div><p className="contest-kicker">2026년 10월 · 에이처치 찬양대회</p><h1>찬양으로 만나는<br/>우리의 무대.</h1><p className="contest-intro">여러분의 응원으로 수상작을 정하는 찬양 나눔 대회. 당신의 찬양을 더 많은 사람에게 전해보세요.</p></div><div className="contest-award"><span>총상금</span><strong>100<span>만 원</span></strong><small>10월 19일 수상 확정</small></div></section>
 <section className="contest-prizes" aria-label="순위별 상금">{CONTEST.prizes.slice(0,4).map((amount,i)=><div key={i}><span>{i<3?`${i+1}위`:"장려상 · 2명"}</span><strong>{i===3&&<small>각 </small>}{amount/10000}<small>만 원</small></strong></div>)}</section>
 <ol className="contest-timeline"><li><b>10.01 — 10.15</b><span>유튜브 영상 링크 접수</span></li><li><b>10.01 — 10.18</b><span>좋아요 · 실시간 순위</span></li><li><b>10.19</b><span>최종 결과 발표</span></li></ol>
 <section className="contest-welcome" aria-label="대회 초대"><div><h2>함께 부르고, 함께 나누는 찬양</h2><p>유튜브 영상 링크로 참여하고, 친구와 이웃을 나의 무대로 초대하세요. 수상 여부와 관계없이 공개 참가작은 대회 후에도 이 페이지에서 감상하고 공유할 수 있습니다.</p></div><div className="contest-welcome-actions"><button className="contest-primary" type="button" onClick={()=>setShareEntry(0)}>대회 소식 공유</button><a href="/praise-contest/contest.ics" download>10월 1일 일정 저장</a></div></section>
 <section className="contest-stage" aria-label="찬양대회 참가 영상"><div className="contest-toolbar"><div><h2>참가 영상 <span>{feed?feed.items.length:"—"}</span></h2><p>{feed?phaseLabels[phase]:"대회 정보를 확인하고 있습니다."}{updated&&` · ${updated} 집계`}</p></div><button className="contest-primary" type="button" onClick={()=>setShowForm(v=>!v)} aria-expanded={showForm} aria-controls="contest-submission">{showForm?"접수 양식 닫기":preview?"접수 양식 미리보기":"＋ 내 영상 등록"}</button></div>
 <p className="contest-invitation"><strong>좋은 찬양은 함께 들을 때 더 멀리 전해집니다.</strong> 마음에 닿은 무대에 하트를 보내고, 소중한 사람에게 나눠주세요.</p>
 {phase==="cancelled"&&<p className="contest-feedback" role="status">참가작이 5개 이하로 접수되어 대회가 취소되었습니다. 투표와 시상은 진행하지 않습니다.</p>}
 <p className="contest-order-note">매일 한 작품에 마음을 전하세요 · 선택한 하트는 다시 눌러 바꿀 수 있어요 <span>누적 좋아요 순 · 동점은 등록순 · 10초마다 갱신</span></p>
 {error&&<div className="contest-feedback" role="alert">{error} <button type="button" onClick={()=>void load()}>다시 불러오기</button></div>}
 {message&&<div className="contest-toast" role="status"><span>{message}</span><button type="button" aria-label="알림 닫기" onClick={()=>setMessage("")}>×</button></div>}
 {showForm&&<form className="contest-form" id="contest-submission" onSubmit={submit}><h3>내 유튜브 영상으로 참가하기</h3><p>영상 링크만 등록하세요. 공개 등록 직후부터 응원이 시작되므로 먼저 등록할수록 응원받을 기간이 길어집니다.</p>{!canSubmit&&<p className="contest-notice">{preview?"예시 화면에서는 실제 접수를 받지 않습니다.":phase==="upcoming"?"10월 1일 00:00부터 등록할 수 있습니다.":"영상 접수가 마감되었습니다."} 모든 일정은 한국 시간입니다.</p>}<fieldset disabled={!canSubmit||busy}><div className="contest-fields"><label>참가자·팀 이름<input name="performer" required minLength={2} maxLength={60} autoComplete="name"/></label><label>찬양 곡명<input name="title" required minLength={2} maxLength={120}/></label><label className="contest-field-wide">내 유튜브 영상 링크<input type="url" name="youtubeUrl" placeholder="https://www.youtube.com/watch?v=…" required maxLength={500}/></label><label>연락 이메일 <small>운영자에게만 공개</small><input type="email" name="contact" required maxLength={160} autoComplete="email"/></label><label>전화번호 <small>수상 연락용</small><input type="tel" name="phone" required maxLength={30} autoComplete="tel"/></label><label>은행명<input name="bank" required minLength={2} maxLength={50} autoComplete="off"/></label><label>예금주<input name="holder" required minLength={2} maxLength={60} autoComplete="off"/></label><label>계좌번호 <small>상금 받을 계좌</small><input name="account" inputMode="numeric" required minLength={8} maxLength={40} autoComplete="off"/></label></div><p>연락처와 계좌 정보는 운영자만 확인합니다. 수상 결과와 계좌 확인 후 상금을 지급합니다.</p><div className="contest-consents"><label><input type="checkbox" name="payoutConsent" required/><span>전화번호·은행명·예금주·계좌번호를 수상 연락과 상금 지급에 사용하는 데 동의합니다. 대회 종료 후 180일 보관하며, <a href="/privacy">정보 처리 안내</a>에서 자세히 확인할 수 있습니다.</span></label><label><input type="checkbox" name="rightsConsent" required/><span>본인이 참여한 찬양 영상이며, 영상·반주·곡의 게시에 필요한 권리를 확인했습니다. 타인의 영상을 대신 등록하지 않습니다.</span></label><label><input type="checkbox" name="ageConsent" required/><span>성인이거나 미성년 참가자의 보호자이며, 영상에 등장하는 참여자의 공개 동의를 받았습니다.</span></label><label><input type="checkbox" name="privacyConsent" required/><span>이름·곡명·영상은 공개되고, 이메일은 접수·수상 연락에 사용되는 데 동의합니다. <a href="#contest-rules">대회 규칙과 정보 처리 안내</a>를 확인했습니다.</span></label></div><button className="contest-primary" type="submit">{busy?"영상을 확인하고 있습니다…":"동의하고 등록하기"}</button></fieldset></form>}
 {!feed&&!error&&<div className="contest-empty" role="status">참가 영상과 집계를 불러오고 있습니다.</div>}
 {feed&&feed.items.length===0&&<div className="contest-empty"><span aria-hidden="true">♫</span><h3>{phase==="upcoming"?"첫 무대가 곧 열립니다.":"아직 등록된 영상이 없습니다."}</h3><p>{phase==="upcoming"?"10월 1일, 본인의 유튜브 찬양 영상 링크를 등록해 주세요.":"접수 기간에 내 유튜브 찬양 영상으로 참여해 주세요."}</p></div>}
 <div className="contest-grid">{feed?.items.map(item=><article className={`contest-card${item.rank===1?" is-leading":""}${highlight===item.id?" is-highlighted":""}`} key={item.id} id={`entry-${item.id}`}><div className="contest-card-top"><span className={item.rank===1?"contest-rank is-first":"contest-rank"}>{item.rank?(feed.finalized&&(item.rank===4||item.rank===5)?"장려상":`${item.rank}위`):`등록 ${item.id}`}</span>{item.prize>0&&<strong className="contest-winner">상금 {item.prize/10000}만 원</strong>}</div><div className="contest-video">{playing===item.id?<><iframe src={`https://www.youtube-nocookie.com/embed/${item.youtubeId}?autoplay=1`} title={`${item.performer} - ${item.title}`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/><button className="contest-stop" type="button" aria-label="영상 닫기" onClick={()=>setPlaying(null)}>×</button></>:<button className="contest-thumbnail" type="button" aria-label={`${item.title} 재생`} onClick={()=>setPlaying(item.id)}><img src={`https://i.ytimg.com/vi/${item.youtubeId}/hqdefault.jpg`} alt="" loading="lazy"/><span aria-hidden="true">▶</span></button>}</div><div className="contest-card-copy"><h3 title={item.title}>{item.title}</h3><p>{item.performer}</p><a className="contest-source" href={`https://www.youtube.com/watch?v=${item.youtubeId}`} target="_blank" rel="noreferrer">유튜브 원본 보기 ↗</a>{preview&&<p className="contest-source">미리보기 영상</p>}<div className="contest-card-actions"><button className={`contest-like${feed.votedEntryId===item.id?" is-liked":""}`} type="button" aria-pressed={feed.votedEntryId===item.id} disabled={!canVote||(feed.votedEntryId!==null&&feed.votedEntryId!==item.id)||liking!==null} onClick={()=>void like(item.id)}><span aria-hidden="true">{feed.votedEntryId===item.id?"♥":"♡"}</span> {liking===item.id?"저장 중":`${feed.votedEntryId===item.id?"응원 중":"좋아요"} ${item.likes.toLocaleString()}`}</button><button type="button" onClick={()=>setShareEntry(shareEntry===item.id?null:item.id)} aria-expanded={shareEntry===item.id}>공유하기</button></div></div></article>)}</div>
 {feed?.votedEntryId&&<p className="contest-vote-note">{Date.parse(feed.serverNow)>=Date.parse(CONTEST.votingEndsAt)-86400000?"오늘의 응원이 완료되었습니다. 10월 19일 최종 결과를 확인해 주세요.":"오늘의 응원이 완료되었습니다. 한국 시간 자정 이후 다시 한 작품을 응원할 수 있습니다."}</p>}
 </section>
 <dialog ref={shareDialog} className="contest-share-dialog" onCancel={()=>setShareEntry(null)} onClose={()=>setShareEntry(null)} onClick={e=>{if(e.target===e.currentTarget)setShareEntry(null);}}>{sharing&&<div><div className="contest-share-heading"><h2>{sharedItem?"이 무대를 함께 나눠요":"찬양의 무대로 초대해요"}</h2><button type="button" aria-label="공유 창 닫기" onClick={()=>setShareEntry(null)}>×</button></div>{sharedItem&&<img className="contest-share-image" src={`https://i.ytimg.com/vi/${sharedItem.youtubeId}/hqdefault.jpg`} alt={sharedItem.title}/>}<p className="contest-share-invitation">{shareText(sharedItem)}</p><div className="contest-share"><label>공유 주소<input aria-label="공유 주소" readOnly value={shareUrl(sharedItem?.id??0)} onFocus={e=>e.currentTarget.select()}/></label><button className="contest-primary" type="button" onClick={()=>void copyInvitation()}>초대 글 복사</button><button type="button" onClick={()=>void copyShare(sharedItem?.id??0)}>링크만 복사</button>{typeof navigator!=="undefined"&&typeof navigator.share==="function"&&<button type="button" onClick={()=>void nativeShare(sharedItem)}>앱으로 공유</button>}</div><small>카카오톡·문자에 초대 글을 붙여넣어 함께 나눠주세요.</small></div>}</dialog>
 <details className="contest-rules" id="contest-rules"><summary>참가·투표·시상 안내</summary><div><h3>일정과 순위</h3><p>한국 시간 2026년 10월 1일 00:00 시작. 영상 접수는 15일 23:59:59까지, 좋아요는 18일 23:59:59까지입니다. 19일 마감된 집계를 고정하여 1·2·3위와 장려상 2명을 확정·발표합니다. 실력 심사 점수 없이 누적 좋아요로 순위를 정합니다. 공개 등록 즉시 투표가 시작되어 등록일에 따라 응원받을 수 있는 기간이 다릅니다. 동점과 좋아요 0개 영상은 등록이 빠른 순으로 정렬합니다. 10월 15일 접수 마감 기준, 참가 조건을 충족한 작품이 5개 이하이면 대회는 자동 취소됩니다. 좋아요 투표도 종료되며 수상자 선정과 상금 지급은 진행하지 않습니다.</p><h3>좋아요와 상금</h3><p>참가와 좋아요는 무료입니다. 한 브라우저에서 하루에 대회 전체 중 한 작품에 좋아요 1개를 줄 수 있습니다. 한국 시간 자정에 새 참여 기회가 생기며, 다음 날 같은 작품이나 다른 작품을 응원할 수 있습니다. 모든 날짜의 좋아요를 누적 집계하며, 당일 누른 하트를 다시 누르면 취소할 수 있으며, 취소 후 다른 작품을 선택할 수 있습니다. 지난 날짜의 좋아요와 투표 종료 후에는 취소할 수 없습니다. 브라우저 쿠키를 삭제하거나 다른 브라우저를 사용하면 동일인을 구별할 수 없으며, 이는 본인인증 방식이 아닙니다. 자동화·반복 조작은 금지합니다. 상금은 1위 50만 원, 2위 30만 원, 3위 10만 원, 장려상 2명 각 5만 원입니다. 최종 집계와 실제 지급 완료는 별개이며, 접수한 지급 정보는 비공개로 보관하며 10월 19일 수상 확정 후 수상자와 계좌를 확인한 순서대로, 확인 완료 후 7영업일 이내 지급합니다.</p><h3>집계 확인과 문의</h3><p>진행 중 집계에 대한 이의는 한국 시간 10월 18일 23:59:59까지 문의 페이지로 보내 주세요. 19일 수상 결과를 확정합니다. 이후 발견된 집계 오류나 영상 권리 문제도 접수하며, 관련 기록을 확인하고 당사자에게 확인 결과와 처리 내용을 안내합니다. 확인 중인 해당 건의 지급은 보류할 수 있으며, 정정이 필요한 경우 사유와 변경 내용을 공지합니다.</p><h3>영상 링크로 참여하기</h3><p>본인의 유튜브 영상 링크만 등록하세요. 공개 등록 직후부터 응원이 시작되므로 먼저 등록할수록 응원받을 기간이 길어집니다. 에이처치 유튜브 채널에도 영상을 올리는 일은 희망하는 참가자와 별도로 협의합니다.</p><h3>정보 처리와 문의</h3><p>참가자명·곡명·유튜브 영상·등록 시각·좋아요 수·순위는 공개합니다. 이메일·전화번호·은행명·예금주·계좌번호·참가 동의 기록은 운영자만 접수·수상 연락·상금 지급 목적으로 확인합니다. 공개 참가작은 대회 후에도 이 페이지에서 소개하며, 원본 공개 중단·삭제 요청·권리 확인에 따라 게시가 종료될 수 있습니다. 공개 자료는 참가작 소개 기간 동안, 비공개 접수 정보는 대회 종료 후 180일이 지나면 운영 처리 시 삭제합니다. 동의 기록은 게시 근거로 보관합니다. 좋아요는 서명된 브라우저 쿠키와 서버의 익명 식별값으로 중복을 제한합니다. 권리·삭제·이의 문의는 <a href="/contact">문의 페이지</a>로 보내 주세요. 이 대회는 YouTube가 후원하거나 운영하지 않습니다. <a href="https://www.youtube.com/howyoutubeworks/policies/community-guidelines/" target="_blank" rel="noreferrer">YouTube 커뮤니티 가이드</a>를 위반하거나 권리가 확인되지 않은 영상은 보류할 수 있습니다.</p></div></details>
 </>;
}
