export const publicRemainingSources = [
  {name:"개동교회",pastor:"윤성철 목사",region:"지역 확인 필요",denomination:"예수교대한성결교회",channelId:"UCPbcdsrE4L-ddzm8dvZsNSw",homepage:"http://www.kaedong.or.kr/"},
  {name:"나사렛교회",pastor:"곽호경 목사",region:"서울",denomination:"대한기독교나사렛성결회",channelId:"UCuT-d12USiePHXy8x58lCTQ"},
  {name:"방화동교회",pastor:"이풍우 목사",region:"서울",denomination:"대한기독교나사렛성결회",channelId:"UCE6T3J_9VTwpRkc2rtqzL1w"},
  {name:"인광교회",pastor:"최정림 목사",region:"경기",denomination:"대한기독교나사렛성결회",channelId:"UCKSYPUyFiPHlyPtNJ8pIldg"},
  {name:"천안제자교회",pastor:"황창선 목사",region:"충남",denomination:"대한기독교나사렛성결회",channelId:"UCfj1IwI2208ynFEbQhzFI-w"},
  {name:"평내행복한교회",pastor:"박우선 목사",region:"경기",denomination:"대한기독교나사렛성결회",channelId:"UCaM2JVTXWDu6hkCNql7LSbA"},
  {name:"복된교회",pastor:"류우열 목사",region:"인천",denomination:"예수교대한성결교회",channelId:"UCvQcJrk9Q7cIOScJafjV0PQ",homepage:"http://www.bokduen.net/"},
  {name:"생명줄교회",pastor:"신동필 목사",region:"지역 확인 필요",denomination:"예수교대한성결교회",channelId:"UCTTFbkUNbP6LzG0cwKugEOA",homepage:"http://www.lifelinemission.org/"},
  {name:"항만선교교회",pastor:"박유석 목사",region:"경기",denomination:"대한기독교나사렛성결회",channelId:"UCNELEeB2CtbcIShJtxnAtUA"},
  {name:"길음교회",pastor:"윤태영 목사",region:"경기",denomination:"대한기독교나사렛성결회",channelId:"UC8nH30xi6FG9zX_wy8W3IAg"},
  {name:"물가에심은나무교회",pastor:"김은엽 목사",region:"경기",denomination:"대한기독교나사렛성결회",channelId:"UCdPg8j2s0ZQ5VPCYfJQqqiw"},
  {name:"행복나누리교회",pastor:"윤기철 목사",region:"충남",denomination:"대한기독교나사렛성결회",channelId:"UC41Phti_5ZDua4iqHd5dd2Q"},
  {name:"광주감리교회",pastor:"최종호 감독",region:"경기 광주",denomination:"기독교대한감리회",channelId:"UC4gQIstDzDhQvbYK4I7cOEQ",homepage:"https://gjmc.kr/"},
  {name:"운정참존교회",pastor:"고병찬 목사",region:"경기 파주",denomination:"대한예수교장로회",channelId:"UCkOkgVhksDPR3vdCjflq2aQ",homepage:"http://www.czch.org/"},
  {name:"서울주교좌성당(성모 마리아와 성 니콜라)",pastor:"김장환 주교",region:"서울 중구",denomination:"대한성공회",channelId:"UCN0jjLjtmHMQan6jHDEf1yw",homepage:"http://www.cathedral.or.kr/"},
  {name:"동탄교회",pastor:"계성남 신부",region:"경기 화성",denomination:"대한성공회",channelId:"UCIG1HLRIQpbLkq8EPht-BNw"},
  {name:"수원교회(성스테반)",pastor:"최용준 신부",region:"경기 수원",denomination:"대한성공회",channelId:"UCfBD3JnzLjQ8rffw00dPytw",homepage:"https://www.suwon1904.kr/"},
  {name:"시냇가푸른나무교회",pastor:"신용백 목사",region:"서울 관악",denomination:"예수교대한성결교회",channelId:"UCYX-dzaODK3-hJwyhiw9whQ",homepage:"http://www.gt21.kr/"},
  {name:"안성중앙교회",pastor:"송용현 목사",region:"경기 안성",denomination:"예수교대한성결교회",channelId:"UCXSbrCYo4KAtENIMwQwE5yQ",homepage:"http://www.ccloud.tv/asjachurch"},
  {name:"안양성결교회",pastor:"강대일 목사",region:"경기 안양",denomination:"예수교대한성결교회",channelId:"UCJqYMj7iaJqZ5C1HWSXXQkA",homepage:"http://www.asc.or.kr/"},
  {name:"원당성결교회",pastor:"이명화 목사",region:"경기 고양",denomination:"예수교대한성결교회",channelId:"UCw87YkmKzf8wOhrqGbJCQzg",homepage:"http://www.wondangchurch.or.kr/"},
  {name:"김해양문교회",pastor:"박병지 목사",region:"경남 김해",denomination:"예수교대한성결교회",channelId:"UCToZgrpKJfbIJqfOBuGSrqQ",homepage:"http://cafe.daum.net/kymch"},
  {name:"순수교회",pastor:"정석한 목사",region:"서울 송파",denomination:"예수교대한성결교회",channelId:"UCOM4xWzGv7PeBlFVPQ_E4tQ",homepage:"http://purechurch.onmam.com/"},
  {name:"평택함께하는교회",pastor:"최준문 목사",region:"경기 평택",denomination:"대한기독교나사렛성결회",channelId:"UCymDmouGJD0BW8iB7kLc5iA"},
  {name:"군산나사렛교회",pastor:"유광열 목사",region:"전북 군산",denomination:"대한기독교나사렛성결회",channelId:"UCxUQzwUDLzIDCNzjLfTzd5Q"},
  {name:"상암동교회",pastor:"신민규 목사",region:"서울 마포",denomination:"대한기독교나사렛성결회",channelId:"UCoKBrzOQ9X_l2wyc2Jn12FA"},
  {name:"진리의기둥교회",pastor:"김환희 목사",region:"경기 평택",denomination:"대한기독교나사렛성결회",channelId:"UCh7NRmhQ4TshmD4M4PQhYRg"},
  {name:"포인트교회",pastor:"박성훈 목사",region:"경기 평택",denomination:"대한기독교나사렛성결회",channelId:"UC3wQo4aDKkPukQVXhX3BWWQ"},
  {name:"주사랑교회(아산)",pastor:"안경모 목사",region:"충남 아산",denomination:"대한기독교나사렛성결회",channelId:"UCx5Zdj9BIMJCRlf_04X5mFQ"},
] as const;
