"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
type Entry={id:number;performer:string;title:string;youtubeId:string;contact:string;sourceFileUrl:string|null;status:string;reuploadStatus:string;reuploadUrl:string|null;adminNote:string|null;consentAt:string;consentVersion:string};
export default function ContestAdmin(){
 const [items,setItems]=useState<Entry[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState<number|null>(null),[loading,setLoading]=useState(true);
 const [payout,setPayout]=useState<{id:number;phone:string;bank:string;holder:string;account:string}|null>(null);
 useEffect(()=>{if(!payout)return;const timer=window.setTimeout(()=>setPayout(null),60000);const hide=()=>{if(document.visibilityState!=="visible")setPayout(null);};document.addEventListener("visibilitychange",hide);return()=>{clearTimeout(timer);document.removeEventListener("visibilitychange",hide);};},[payout]);
 async function revealPayout(id:number){setPayout(null);try{const r=await fetch("/api/admin/praise-contest/payout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id}),cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setPayout({id,...d.details});}catch(e){setMessage(e instanceof Error?e.message:"지급 정보 조회 실패");}}
 const load=useCallback(async()=>{try{const r=await fetch("/api/admin/praise-contest",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);}catch(e){setMessage(e instanceof Error?e.message:"불러오기 실패");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 async function save(event:FormEvent<HTMLFormElement>,id:number){event.preventDefault();setBusy(id);setMessage("");const data=new FormData(event.currentTarget);try{const r=await fetch("/api/admin/praise-contest",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(data),id,rightsReviewed:data.has("rightsReviewed"),reuploadAgreed:data.has("reuploadAgreed")})});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage("저장했습니다.");await load();}catch(e){setMessage(e instanceof Error?e.message:"저장 실패");}finally{setBusy(null);}}
 return <>{message&&<p className="contest-feedback" role="status">{message}</p>}<button type="button" onClick={()=>void load()}>새로고침</button>{loading?<p>접수 정보를 불러오고 있습니다.</p>:items.length===0?<p>아직 접수된 영상이 없습니다.</p>:<div className="contest-admin-list">{items.map(item=><article key={item.id} className="contest-admin-item"><h2>#{item.id} {item.performer} · {item.title}</h2><p>이메일: {item.contact}</p><button type="button" onClick={()=>void revealPayout(item.id)}>전화·입금 계좌 확인</button>{payout?.id===item.id&&<div className="contest-notice"><p>전화: {payout.phone}</p><p>은행: {payout.bank} · 예금주: {payout.holder}</p><p>계좌: {payout.account}</p><small>입력된 정보이며 은행 확인·송금은 별도로 진행합니다. 1분 후 화면에서 가려집니다.</small><button type="button" onClick={()=>setPayout(null)}>정보 가리기</button></div>}<p><a href={`https://www.youtube.com/watch?v=${item.youtubeId}`} target="_blank" rel="noreferrer">참가자 유튜브 원본</a> · {item.sourceFileUrl?<a href={item.sourceFileUrl} target="_blank" rel="noreferrer">제출한 원본 파일 링크</a>:"접수 시 원본 제출 없음"}</p><p>참가 동의: {item.consentAt} · {item.consentVersion}</p><form onSubmit={e=>void save(e,item.id)}><label>공개 상태 <select name="status" defaultValue={item.status}><option value="published">공개</option><option value="held">보류</option></select></label><label>재업로드 <select name="reuploadStatus" defaultValue={item.reuploadStatus}><option value="not_requested">별도 협의 전</option><option value="awaiting_source">원본 대기</option><option value="rights_review">권리 확인 중</option><option value="ready">업로드 준비 완료</option><option value="uploaded">게시 완료</option></select></label><label>에이처치 게시 링크 <input type="url" name="reuploadUrl" defaultValue={item.reuploadUrl??""}/></label><label>처리 사유 <input name="note" maxLength={500} defaultValue={item.adminNote??""}/></label><label><input type="checkbox" name="reuploadAgreed"/> 참가자와 별도 재업로드 합의 확인</label><label><input type="checkbox" name="rightsReviewed"/> 원본·곡·반주·출연자 게시 권리 확인</label><button type="submit" disabled={busy!==null}>{busy===item.id?"저장 중":"저장"}</button></form></article>)}</div>}</>;
}
