"use client";
import PaymentsPanel from "./payments-panel";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
type Entry={id:number;performer:string;title:string;youtubeId:string;contact:string;sourceFileUrl:string|null;status:string;reuploadStatus:string;reuploadUrl:string|null;adminNote:string|null;consentAt:string;consentVersion:string};
type View={q:string;status:string;sort:string;page:number};
export default function ContestAdmin(){
 const [items,setItems]=useState<Entry[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState<number|null>(null),[loading,setLoading]=useState(true);
 const [view,setView]=useState<View>({q:"",status:"all",sort:"newest",page:1}),[search,setSearch]=useState("");
 const [counts,setCounts]=useState({total:0,published:0,held:0}),[pagination,setPagination]=useState({page:1,pageSize:20,total:0,totalPages:1}),[listError,setListError]=useState("");
 const [openId,setOpenId]=useState<number|null>(null),opened=useRef<number|null>(null),pending=useRef<AbortController|null>(null),sequence=useRef(0),contactRequest=useRef(0);
 const [payout,setPayout]=useState<{id:number;phone:string;bank?:string;holder?:string;account?:string}|null>(null);
 const clearPayout=useCallback(()=>{contactRequest.current++;setPayout(null);},[]);
 const closeDetail=useCallback(()=>{opened.current=null;setOpenId(null);clearPayout();},[clearPayout]);
 function changeView(change:Partial<View>){closeDetail();setView(current=>({...current,...change,page:change.page??1}));}
 function toggleDetail(id:number){const next=opened.current===id?null:id;opened.current=next;setOpenId(next);clearPayout();}
 useEffect(()=>{if(!payout)return;const timer=window.setTimeout(()=>setPayout(null),60000);const hide=()=>{if(document.visibilityState!=="visible")clearPayout();};document.addEventListener("visibilitychange",hide);return()=>{clearTimeout(timer);document.removeEventListener("visibilitychange",hide);};},[payout,clearPayout]);
 async function revealPayout(id:number){clearPayout();const current=contactRequest.current;try{const r=await fetch("/api/admin/praise-contest/payout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id}),cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);if(current===contactRequest.current&&opened.current===id)setPayout({id,...d.details});}catch(e){setMessage(e instanceof Error?e.message:"지급 정보 조회 실패");}}
 const load=useCallback(async()=>{
  pending.current?.abort();const controller=new AbortController();pending.current=controller;const current=++sequence.current;setLoading(true);setListError("");clearPayout();
  try{const params=new URLSearchParams({q:view.q,status:view.status,sort:view.sort,page:String(view.page)}),r=await fetch(`/api/admin/praise-contest?${params}`,{cache:"no-store",signal:controller.signal}),d=await r.json();if(!r.ok)throw new Error(d.error);if(current!==sequence.current)return;setItems(d.items);setCounts(d.counts);setPagination(d.pagination);setOpenId(previous=>{if(previous!==null&&d.items.some((item:Entry)=>item.id===previous))return previous;opened.current=null;return null;});}
  catch(error){if(controller.signal.aborted||current!==sequence.current)return;setItems([]);closeDetail();setListError(error instanceof Error?error.message:"불러오기 실패");}
  finally{if(current===sequence.current)setLoading(false);}
 },[view,closeDetail,clearPayout]);
 useEffect(()=>{void load();return()=>pending.current?.abort();},[load]);
 useEffect(()=>()=>{opened.current=null;contactRequest.current++;},[]);
 async function save(event:FormEvent<HTMLFormElement>,id:number){event.preventDefault();setBusy(id);setMessage("");const data=new FormData(event.currentTarget);try{const r=await fetch("/api/admin/praise-contest",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(data),id,rightsReviewed:data.has("rightsReviewed"),reuploadAgreed:data.has("reuploadAgreed")})});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage("저장했습니다.");await load();}catch(e){setMessage(e instanceof Error?e.message:"저장 실패");}finally{setBusy(null);}}
 async function hide(form:HTMLFormElement,id:number){const note=new FormData(form).get("note");if(typeof note!=="string"||!note.trim()){setMessage("공개 목록에서 삭제할 사유를 적어 주세요.");return;}if(!window.confirm("공개 목록에서 삭제하시겠습니까? 참가 정보와 좋아요는 보존되며 관리자에서 다시 공개할 수 있습니다."))return;setBusy(id);setMessage("");clearPayout();try{const r=await fetch("/api/admin/praise-contest",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action:"hide",note})});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage("공개 목록에서 삭제했습니다. 공개 상태를 ‘공개’로 바꾸고 저장하면 복구됩니다.");await load();}catch(e){setMessage(e instanceof Error?e.message:"삭제 실패");}finally{setBusy(null);}}
 return <>
  {message&&<p className="contest-feedback" role="status">{message}</p>}
  <div className="contest-admin-toolbar"><div><h2>참가작 관리</h2><p>{loading?"접수 정보를 확인하고 있습니다.":`전체 ${counts.total}건 · 공개 ${counts.published}건 · 비공개 ${counts.held}건`}</p></div><button type="button" disabled={busy!==null||loading} onClick={()=>void load()}>목록 새로고침</button></div>
  <form className="contest-admin-search" onSubmit={event=>{event.preventDefault();changeView({q:search.trim()});}}><label>참가작 검색<div><input type="search" value={search} maxLength={80} onChange={event=>setSearch(event.target.value)} placeholder="참가자·팀 이름, 곡명 또는 접수번호" disabled={busy!==null}/><button type="submit" disabled={busy!==null}>검색</button></div></label><label>공개 상태<select value={view.status} onChange={event=>changeView({status:event.target.value})} disabled={busy!==null}><option value="all">전체 상태</option><option value="published">공개</option><option value="held">삭제·보류 (비공개)</option></select></label><label>정렬<select value={view.sort} onChange={event=>changeView({sort:event.target.value})} disabled={busy!==null}><option value="newest">최근 접수순</option><option value="oldest">오래된 접수순</option><option value="name">참가자 이름순</option></select></label>{(view.q||view.status!=="all")&&<button className="contest-admin-reset" type="button" disabled={busy!==null} onClick={()=>{setSearch("");changeView({q:"",status:"all"});}}>검색·필터 초기화</button>}</form>
  {loading?<p className="contest-admin-empty">접수 정보를 불러오고 있습니다.</p>:listError?<p className="contest-feedback" role="alert">{listError} 목록 새로고침으로 다시 시도해 주세요.</p>:items.length===0?<p className="contest-admin-empty">{view.q||view.status!=="all"?"검색 조건에 맞는 참가작이 없습니다.":"아직 접수된 영상이 없습니다."}</p>:<div className="contest-admin-list">{items.map(item=><article key={item.id} className={`contest-admin-item contest-entry-card contest-entry-row${openId===item.id?" is-open":""}`}>
   <div className="contest-entry-summary"><span className="contest-entry-number">#{item.id}</span><div className="contest-entry-summary-copy"><h3>{item.performer}</h3><p>{item.title}</p></div><span className={`contest-entry-status${item.status==="held"?" is-held":""}`}>{item.status==="held"?"비공개·삭제":"공개 중"}</span><button type="button" disabled={busy!==null} aria-expanded={openId===item.id} aria-controls={`contest-entry-detail-${item.id}`} onClick={()=>toggleDetail(item.id)}>{openId===item.id?"상세 닫기":"상세·수정"}</button></div>
   {openId===item.id&&<div className="contest-entry-expanded" id={`contest-entry-detail-${item.id}`}>
   <div className="contest-entry-contact"><span>이메일 <a href={`mailto:${item.contact}`}>{item.contact}</a></span><button type="button" onClick={()=>void revealPayout(item.id)}>비공개 연락정보 확인</button></div>
   {payout?.id===item.id&&<div className="contest-notice"><p>전화: {payout.phone}</p>{payout.bank&&payout.holder&&payout.account?<><p>은행: {payout.bank} · 예금주: {payout.holder}</p><p>계좌: {payout.account}</p></>:<p>신청 시 계좌정보를 받지 않았습니다. 수상 확정 후 수상자에게만 연락해 별도로 확인하세요.</p>}<small>기존에 제공된 계좌정보가 있으면 함께 표시합니다. 은행 확인·송금은 별도로 진행하며, 1분 후 화면에서 가려집니다.</small><button type="button" onClick={()=>setPayout(null)}>정보 가리기</button></div>}
   <div className="contest-entry-sources"><a href={`https://www.youtube.com/watch?v=${item.youtubeId}`} target="_blank" rel="noreferrer">유튜브 원본 보기 ↗</a>{item.sourceFileUrl?<a href={item.sourceFileUrl} target="_blank" rel="noreferrer">제출한 원본 파일 ↗</a>:<span>접수 시 원본 파일 제출 없음</span>}</div>
   <form className="contest-entry-form" key={`${item.id}:${item.status}:${item.performer}:${item.title}`} onSubmit={e=>void save(e,item.id)}>
    <div className="contest-entry-fields"><label>참가자·팀 이름<input name="performer" required minLength={2} maxLength={60} defaultValue={item.performer}/></label><label>곡명<input name="title" required minLength={2} maxLength={120} defaultValue={item.title}/></label></div>
    <div className="contest-entry-fields contest-entry-state-fields"><label>공개 상태<select name="status" defaultValue={item.status}><option value="published">공개</option><option value="held">삭제·보류 (비공개)</option></select></label><label>처리 사유<input name="note" required maxLength={500} defaultValue={item.adminNote??""} placeholder="수정·공개·삭제 사유를 적어 주세요"/></label></div>
    <details className="contest-entry-details"><summary>재업로드·게시 권리 관리</summary><p>원본과 게시 권리를 확인한 영상만 별도로 업로드하세요.</p><div className="contest-entry-fields"><label>재업로드 상태<select name="reuploadStatus" defaultValue={item.reuploadStatus}><option value="not_requested">별도 협의 전</option><option value="awaiting_source">원본 대기</option><option value="rights_review">권리 확인 중</option><option value="ready">업로드 준비 완료</option><option value="uploaded">게시 완료</option></select></label><label>에이처치 게시 링크<input type="url" name="reuploadUrl" defaultValue={item.reuploadUrl??""}/></label></div><div className="contest-entry-checks"><label><input type="checkbox" name="reuploadAgreed"/> 참가자와 별도 재업로드 합의 확인</label><label><input type="checkbox" name="rightsReviewed"/> 원본·곡·반주·출연자 게시 권리 확인</label></div></details>
    <div className="contest-entry-actions"><button className="contest-primary" type="submit" disabled={busy!==null}>{busy===item.id?"저장 중":"수정 저장"}</button><button className="contest-entry-delete" type="button" disabled={busy!==null||item.status==="held"} onClick={e=>{if(e.currentTarget.form)void hide(e.currentTarget.form,item.id);}}>공개 목록에서 삭제</button><p>삭제해도 참가 정보와 좋아요는 보존됩니다. ‘공개’로 바꾸고 저장하면 복구됩니다.</p></div>
   </form>
   <details className="contest-entry-record"><summary>접수·동의 기록</summary><p>참가 동의: {item.consentAt} · {item.consentVersion}</p></details>
   </div>}
  </article>)}</div>}
  {!listError&&<nav className="contest-admin-pagination" aria-label="참가작 페이지"><p>{pagination.total===0?"검색 결과 0건":`${(pagination.page-1)*pagination.pageSize+1}–${Math.min(pagination.page*pagination.pageSize,pagination.total)} / ${pagination.total}건`} · {pagination.page} / {pagination.totalPages}페이지</p><div><button type="button" disabled={loading||busy!==null||pagination.page<=1} onClick={()=>changeView({page:pagination.page-1})}>이전</button><button type="button" disabled={loading||busy!==null||pagination.page>=pagination.totalPages} onClick={()=>changeView({page:pagination.page+1})}>다음</button></div></nav>}
  <div className="contest-admin-payment-area"><PaymentsPanel/></div>
 </>;
}
