"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
type Winner={id:number;performer:string;title:string;rank:number;prize:number};
type Payment={attemptId:string;entryId:number;status:string;amount:number;reference:string|null;note:string};
export default function PaymentsPanel(){
 const [data,setData]=useState<{winners:Winner[];payments:Payment[]}|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch("/api/admin/praise-contest/payments",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setMessage(e instanceof Error?e.message:"조회 실패");}},[]);
 useEffect(()=>{void load();},[load]);
 async function save(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();if(busy)return;setBusy(true);const form=e.currentTarget,d=new FormData(form);try{const r=await fetch("/api/admin/praise-contest/payments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(d),id,recipientChecked:d.has("recipientChecked"),accountChecked:d.has("accountChecked"),issuesChecked:d.has("issuesChecked"),bankConfirmed:d.has("bankConfirmed")})});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage("지급 처리 기록을 저장했습니다. 이 화면은 은행 송금을 실행하지 않습니다.");form.reset();}catch(e){setMessage(e instanceof Error?e.message:"저장 실패");}finally{await load();setBusy(false);}}
 return <details className="contest-rules"><summary>수상자 지급 관리</summary><p>수상자 확인 → 계좌 확인 → 이체 처리 예약 → 실제 은행 이체 → 거래번호 기록. 처리 중인 건은 다른 관리자가 다시 예약할 수 없습니다.</p>{message&&<p role="status">{message}</p>}<button type="button" onClick={()=>void load()}>지급 기록 새로고침</button>{data?.winners.length===0&&<p>10월 19일 확정 수상자가 이곳에 표시됩니다.</p>}{data?.winners.map(w=>{const p=data.payments.find(p=>p.entryId===w.id);return <article className="contest-admin-item" key={w.id}><h3>{w.rank<=3?`${w.rank}위`:"장려상"} · {w.performer} · {w.prize.toLocaleString()}원</h3><p>상태: {p?.status==="paid"?"지급 완료":p?.status==="processing"?"이체 확인 중":p?.status==="failed"?"은행 미입금 확인":"지급 준비"}</p>{p?.reference&&<p>거래번호: {p.reference}</p>}{p?.status!=="paid"&&<form onSubmit={e=>void save(e,w.id)}>{p?.status==="processing"?<><input type="hidden" name="attemptId" value={p.attemptId}/><label>은행 확인 결과<select name="action"><option value="paid">이체 완료</option><option value="failed">미입금 확인</option></select></label><label>거래번호<input name="reference" maxLength={100}/></label><label><input type="checkbox" name="bankConfirmed" required/> 은행의 실제 처리 결과를 확인했습니다</label></>:<><input type="hidden" name="action" value="reserve"/><label><input type="checkbox" name="recipientChecked" required/> 수상자·영상 권리 확인</label><label><input type="checkbox" name="accountChecked" required/> 예금주·계좌 확인</label><label><input type="checkbox" name="issuesChecked" required/> 관련 문의 처리 확인</label></>}<label>처리 사유<input name="note" required minLength={5} maxLength={500}/></label><button disabled={busy} type="submit">{p?.status==="processing"?"은행 결과 기록":"이체 처리 예약"}</button></form>}</article>;})}</details>;
}
